${OVERWRITE} DROP TABLE IF EXISTS ${TABLE_NAME};

CREATE TABLE ${TABLE_NAME} (
  ID INTEGER UNSIGNED NOT NULL,
  VER SMALLINT(6) NOT NULL,
  LANG SMALLINT UNSIGNED NOT NULL,
  ISMAX_VER BOOLEAN NOT NULL,
  ISLIVE_VER BOOLEAN NOT NULL,
  POSITIONS VARCHAR(1024) NULL,

  ${STRING_TIMES} STRING${INDEX} VARCHAR(1024) CHARACTER SET UTF8,
  ${BIGINT_TIMES} BIGINT${INDEX} BIGINT,
  ${DOUBLE_TIMES} DOUBLE${INDEX} DOUBLE,
  ${SELECT_TIMES} SELECT${INDEX} INT UNSIGNED DEFAULT 0,
  ${TEXT_TIMES} TEXT${INDEX} LONGTEXT CHARACTER SET UTF8,

  PRIMARY KEY (ID,VER,LANG),

  ${SELECT_TIMES} FOREIGN KEY FK_${TABLE_NAME}_SELECT${INDEX}(SELECT${INDEX}) REFERENCES FXS_SELECTLIST_ITEM(ID),

  FOREIGN KEY FK_${TABLE_NAME}_LANG(LANG) REFERENCES FXS_LANG(LANG_CODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
COMMENT='Flat storage table'
DEFAULT CHARSET = LATIN1
ROW_FORMAT=DYNAMIC;

${STRING_TIMES} CREATE INDEX FXI_${TABLE_NAME}_STRING${INDEX}   ON ${TABLE_NAME}(STRING${INDEX});
${BIGINT_TIMES} CREATE INDEX FXI_${TABLE_NAME}_BIGINT${INDEX}   ON ${TABLE_NAME}(BIGINT${INDEX});
${DOUBLE_TIMES} CREATE INDEX FXI_${TABLE_NAME}_DOUBLE${INDEX}   ON ${TABLE_NAME}(DOUBLE${INDEX});