import com.flexive.shared.CacheAdmin
import com.flexive.shared.EJBLookup
import com.flexive.shared.exceptions.FxEntryExistsException
import com.flexive.shared.scripting.FxScriptEvent
import com.flexive.shared.scripting.FxScriptInfo
import com.flexive.shared.scripting.groovy.GroovyTypeBuilder
import com.flexive.shared.security.ACLCategory
import com.flexive.shared.structure.*
import com.flexive.shared.value.FxString

println "Creating newsletter types ... "

// *******************************
// Newsletter types
// *******************************

def builder


new GroovyTypeBuilder().newsletter(
	label: new FxString(true, 2, "Newsletter"),
	acl: CacheAdmin.environment.getACL(ACLCategory.STRUCTURE.getDefaultId()),
	languageMode: LanguageMode.Multiple,
	trackHistory: false,
	typeMode: TypeMode.Content,
	maxVersions: -1L,
	storageMode: TypeStorageMode.Hierarchical,
	useInstancePermissions: true,
	usePropertyPermissions: false,
	useStepPermissions: true,
	useTypePermissions: true,
	usePermissions: true)

builder = new GroovyTypeBuilder("NEWSLETTER")
builder {
	name(
		label: new FxString(true, 1, "Name"),
		hint: new FxString(true, 1, ""),
		alias: "NAME",
		defaultMultiplicity: 1,
		dataType: FxDataType.String1024,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		assignment: "ROOT/CAPTION")
  uniquename( 
      label: new FxString(true, 1, "Unique Name").setTranslation(2, "Interne Bezeichnung"),
      hint: new FxString(true, 1, ""),
      alias: "UNIQUENAME",
      defaultMultiplicity: 1,
      multilang: false,
      dataType: FxDataType.String1024,
      acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
      multiplicity: new FxMultiplicity(0,1),
      overrideACL: true,
      overrideMultiplicity: true,
      overrideInOverview: true,
      overrideMaxLength: false,
      overrideMultiline: true,
      overrideSearchable: true,
      overrideUseHtmlEditor: true,
      overrideMultilang: false,
      searchable: true,
      fullTextIndexed: true,
      multiline: false,
      inOverview: false,
      useHtmlEditor: false,
      uniqueMode: UniqueMode.DerivedTypes,
      enabled: true,
      "SHOW.OVERVIEW": "0",
      "MULTILINE": "0",
      "SEARCHABLE": "1",
      "HTML.EDITOR": "0")
	description(
		label: new FxString(true, 1, "Description"),
		hint: new FxString(true, 1, ""),
		alias: "DESCRIPTION",
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.Text,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(0,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: true,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "1",
		"MULTILANG": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
  smtpServer(
		label: new FxString(true, 1, "SMTP Server"),
		hint: new FxString(true, 1, ""),
		alias: "SMTPSERVER",
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.Text,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: true,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "1",
		"MULTILANG": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
  act_url(
		label: new FxString(true, 1, "Activation Base URL"),
		hint: new FxString(true, 1, ""),
		alias: "ACTURL",
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.Text,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: true,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "1",
		"MULTILANG": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
  cancel_url(
		label: new FxString(true, 1, "Cancellation Base URL"),
		hint: new FxString(true, 1, ""),
		alias: "CANCELURL",
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.Text,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: true,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "1",
		"MULTILANG": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
  act_from(
		label: new FxString(true, 1, "Sender (for activation email)"),
		hint: new FxString(true, 1, ""),
		alias: "ACT_FROM",
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.String1024,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
    act_reply_to(
		label: new FxString(true, 1, "Reply To (activation email)"),
		hint: new FxString(true, 1, "Reply To email address for activation email (optional)"),
		alias: "ACT_REPLY_TO",
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.String1024,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(0,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
  activationsubject(
		label: new FxString(true, 1, "Activation Subject"),
		hint: new FxString(true, 1, ""),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.String1024,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
	activationcontentplain(
		label: new FxString(true, 1, "Activation Content Plain"),
		hint: new FxString(true, 1, "Valid tags/codes: {{NAME}}, {{SURNAME}}, {{SALUTATION}}, {{EMAIL}}, {{HAS_NAME_START}}...{{HAS_NAME_END}}, {{HAS_SALUTATION_START}}...{{HAS_SALUTATION_END}}, {{ACTIVATION_URL}}").setTranslation(2, "Gültige Platzhalter/Codes: {{NAME}}, {{SURNAME}}, {{SALUTATION}}, {{EMAIL}}, {{HAS_NAME_START}}...{{HAS_NAME_END}}, {{HAS_SALUTATION_START}}...{{HAS_SALUTATION_END}}, {{ACTIVATION_URL}}"),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.String1024,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: true,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "1",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
  activationcontenthtml(
		label: new FxString(true, 1, "Activation Content HTML"),
		hint: new FxString(true, 1, "Valid tags/codes: {{NAME}}, {{SURNAME}}, {{SALUTATION}}, {{EMAIL}}, {{HAS_NAME_START}}...{{HAS_NAME_END}}, {{HAS_SALUTATION_START}}...{{HAS_SALUTATION_END}}, {{ACTIVATION_URL}}").setTranslation(2, "Gültige Platzhalter/Codes: {{NAME}}, {{SURNAME}}, {{SALUTATION}}, {{EMAIL}}, {{HAS_NAME_START}}...{{HAS_NAME_END}}, {{HAS_SALUTATION_START}}...{{HAS_SALUTATION_END}}, {{ACTIVATION_URL}}"),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.HTML,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: true,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "1")
  sendwelcome(
		label: new FxString(true, 1, "Send Welcome email"),
		hint: new FxString(true, 1, ""),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.Boolean,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
  welcome_from(
		label: new FxString(true, 1, "Sender (for welcome email)"),
		hint: new FxString(true, 1, ""),
		alias: "WELCOME_FROM",
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.String1024,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
    welcome_reply_to(
		label: new FxString(true, 1, "Reply To (welcome email)"),
		hint: new FxString(true, 1, "Reply To email address for welcome email (optional)"),
		alias: "WELCOME_REPLY_TO",
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.String1024,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(0,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
  welcomesubject(
		label: new FxString(true, 1, "Welcome Subject"),
		hint: new FxString(true, 1, ""),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.String1024,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
	welcomecontentplain(
		label: new FxString(true, 1, "Welcome Content Plain"),
		hint: new FxString(true, 1, "Valid tags/codes: {{NAME}}, {{SURNAME}}, {{SALUTATION}}, {{EMAIL}}, {{HAS_NAME_START}}...{{HAS_NAME_END}}, {{HAS_SALUTATION_START}}...{{HAS_SALUTATION_END}}, {{CANCELLATION_URL}}").setTranslation(2, "Gültige Platzhalter/Codes: {{NAME}}, {{SURNAME}}, {{SALUTATION}}, {{EMAIL}}, {{HAS_NAME_START}}...{{HAS_NAME_END}}, {{HAS_SALUTATION_START}}...{{HAS_SALUTATION_END}}, {{CANCELLATION_URL}}"),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.String1024,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: true,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "1",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
  welcomecontenthtml(
		label: new FxString(true, 1, "Welcome Content HTML"),
		hint: new FxString(true, 1, "Valid tags/codes: {{NAME}}, {{SURNAME}}, {{SALUTATION}}, {{EMAIL}}, {{HAS_NAME_START}}...{{HAS_NAME_END}}, {{HAS_SALUTATION_START}}...{{HAS_SALUTATION_END}}, {{CANCELLATION_URL}}").setTranslation(2, "Gültige Platzhalter/Codes: {{NAME}}, {{SURNAME}}, {{SALUTATION}}, {{EMAIL}}, {{HAS_NAME_START}}...{{HAS_NAME_END}}, {{HAS_SALUTATION_START}}...{{HAS_SALUTATION_END}}, {{CANCELLATION_URL}}"),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.HTML,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: true,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "1")
}

new GroovyTypeBuilder().newsletter_message(
	label: new FxString(true, 1, "Newsletter Message"),
	acl: CacheAdmin.environment.getACL(ACLCategory.STRUCTURE.getDefaultId()),
	languageMode: LanguageMode.Multiple,
	trackHistory: false,
	typeMode: TypeMode.Content,
	maxVersions: -1L,
	storageMode: TypeStorageMode.Hierarchical,
	useInstancePermissions: true,
	usePropertyPermissions: false,
	useStepPermissions: true,
	useTypePermissions: true,
	usePermissions: true)

builder = new GroovyTypeBuilder("NEWSLETTER_MESSAGE")
builder {
	title(
		label: new FxString(true, 1, "Message Subject"),
		hint: new FxString(true, 1, ""),
		alias: "TITLE",
		defaultMultiplicity: 1,
		assignment: "ROOT/CAPTION")
    from(
		label: new FxString(true, 1, "Sender (from email)"),
		hint: new FxString(true, 1, ""),
		alias: "FROM",
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.String1024,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
    reply_to(
		label: new FxString(true, 1, "Reply To"),
		hint: new FxString(true, 1, "Reply To email address for sent out emails (optional)"),
		alias: "REPLY_TO",
        autoUniquePropertyName: true,
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.String1024,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(0,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
	newsletter(
		label: new FxString(true, 1, "Newsletter"),
		hint: new FxString(true, 1, ""),
		alias: "NEWSLETTER",
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.Reference,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		referencedType: CacheAdmin.getEnvironment().getType("NEWSLETTER"),
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
	content_plain(
		label: new FxString(true, 1, "Content Plaintext"),
        hint: new FxString(true, 1, "Valid tags/codes: {{NAME}}, {{SURNAME}}, {{SALUTATION}}, {{EMAIL}}, {{HAS_NAME_START}}...{{HAS_NAME_END}}, {{HAS_SALUTATION_START}}...{{HAS_SALUTATION_END}}, {{CANCELLATION_URL}}").setTranslation(2, "Gültige Platzhalter/Codes: {{NAME}}, {{SURNAME}}, {{SALUTATION}}, {{EMAIL}}, {{HAS_NAME_START}}...{{HAS_NAME_END}}, {{HAS_SALUTATION_START}}...{{HAS_SALUTATION_END}}, {{CANCELLATION_URL}}"),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.Text,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: true,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "1",
		"MULTILANG": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
	content_html(
		label: new FxString(true, 1, "Content HTML"),
		hint: new FxString(true, 1, "Valid tags/codes: {{NAME}}, {{SURNAME}}, {{SALUTATION}}, {{EMAIL}}, {{HAS_NAME_START}}...{{HAS_NAME_END}}, {{HAS_SALUTATION_START}}...{{HAS_SALUTATION_END}}, {{CANCELLATION_URL}}").setTranslation(2, "Gültige Platzhalter/Codes: {{NAME}}, {{SURNAME}}, {{SALUTATION}}, {{EMAIL}}, {{HAS_NAME_START}}...{{HAS_NAME_END}}, {{HAS_SALUTATION_START}}...{{HAS_SALUTATION_END}}, {{CANCELLATION_URL}}"),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.HTML,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: true,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"MULTILANG": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "1")
  attachment(
		label: new FxString(true, 1, "Attachment"),
		hint: new FxString(true, 1, ""),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.Binary,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(0,2147483647),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
}

new GroovyTypeBuilder().newsletter_subscriber(
	label: new FxString(true, 1, "Newsletter Subscriber"),
	acl: CacheAdmin.environment.getACL(ACLCategory.STRUCTURE.getDefaultId()),
	languageMode: LanguageMode.Multiple,
	trackHistory: false,
	typeMode: TypeMode.Content,
	maxVersions: -1L,
	storageMode: TypeStorageMode.Hierarchical,
	useInstancePermissions: true,
	usePropertyPermissions: false,
	useStepPermissions: true,
	useTypePermissions: true,
	usePermissions: true)

builder = new GroovyTypeBuilder("NEWSLETTER_SUBSCRIBER")
builder {
    salutation(
		label: new FxString(true, 2, "Anrede").setTranslation(1, "Salutation"),
		hint: new FxString(true, 1, ""),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.String1024,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(0,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
	name(
		label: new FxString(true, 1, "Name"),
		hint: new FxString(true, 1, ""),
		alias: "NAME",
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.String1024,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(0,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
	surname(
		label: new FxString(true, 1, "Surname"),
		hint: new FxString(true, 1, ""),
		alias: "SURNAME",
		defaultMultiplicity: 1,
		dataType: FxDataType.String1024,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		assignment: "ROOT/CAPTION")
	email(
		label: new FxString(true, 1, "eMail"),
		hint: new FxString(true, 1, ""),
		alias: "EMAIL",
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.String1024,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.DerivedTypes,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
    code(
		label: new FxString(true, 1, "CODE"),
		hint: new FxString(true, 1, ""),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.String1024,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
	sendplain(
		label: new FxString(true, 1, "Send plain text"),
		hint: new FxString(true, 1, ""),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.Boolean,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
	sendhtml(
		label: new FxString(true, 1, "Send HTML Text"),
		hint: new FxString(true, 1, ""),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.Boolean,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
	newsletter(
		label: new FxString(true, 1, "Subscribed Newsletter"),
		hint: new FxString(true, 1, ""),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.Reference,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(0,2147483647),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		referencedType: CacheAdmin.getEnvironment().getType("NEWSLETTER"),
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
}



new GroovyTypeBuilder().newsletter_protocol(
	label: new FxString(true, 1, "Newsletter Protocol"),
	acl: CacheAdmin.environment.getACL(ACLCategory.STRUCTURE.getDefaultId()),
	languageMode: LanguageMode.Multiple,
	trackHistory: false,
	typeMode: TypeMode.Content,
	maxVersions: -1L,
	storageMode: TypeStorageMode.Hierarchical,
	useInstancePermissions: true,
	usePropertyPermissions: false,
	useStepPermissions: true,
	useTypePermissions: true,
	usePermissions: true)

builder = new GroovyTypeBuilder("NEWSLETTER_PROTOCOL")
builder {
	sent(
		label: new FxString(true, 1, "Date sent"),
		hint: new FxString(true, 1, ""),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.DateTime,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
	newsletter(
		label: new FxString(true, 1, "Newsletter"),
		hint: new FxString(true, 1, ""),
		alias: "NEWSLETTER",
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.Reference,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		referencedType: CacheAdmin.getEnvironment().getType("NEWSLETTER"),
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
    message(
		label: new FxString(true, 1, "Message"),
		hint: new FxString(true, 1, ""),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.Reference,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(1,1),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		referencedType: CacheAdmin.getEnvironment().getType("NEWSLETTER_MESSAGE"),
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
	success(
		label: new FxString(true, 1, "Success"),
		hint: new FxString(true, 1, ""),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.Reference,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(0,2147483647),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		referencedType: CacheAdmin.getEnvironment().getType("NEWSLETTER_SUBSCRIBER"),
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
	failure(
		label: new FxString(true, 1, "Failure"),
		hint: new FxString(true, 1, ""),
		defaultMultiplicity: 1,
		multilang: false,
		dataType: FxDataType.Reference,
		acl: CacheAdmin.getEnvironment().getACL(ACLCategory.STRUCTURE.getDefaultId()),
		multiplicity: new FxMultiplicity(0,2147483647),
		overrideACL: true,
		overrideMultiplicity: true,
		overrideInOverview: true,
		overrideMaxLength: false,
		overrideMultiline: true,
		overrideSearchable: true,
		overrideUseHtmlEditor: true,
		overrideMultilang: false,
		searchable: true,
		fullTextIndexed: true,
		multiline: false,
		inOverview: false,
		useHtmlEditor: false,
		uniqueMode: UniqueMode.None,
		enabled: true,
		referencedType: CacheAdmin.getEnvironment().getType("NEWSLETTER_SUBSCRIBER"),
		"SHOW.OVERVIEW": "0",
		"MULTILINE": "0",
		"SEARCHABLE": "1",
		"HTML.EDITOR": "0")
}

// *******************************
// Script Assignments
// *******************************

def scriptCode

// SCRIPT OVERRIDE ********
boolean scriptOverride = true
// ************************

// SCRIPTS ATTACHED TO TYPE EVENTS

def FxType currentType
def FxScriptInfo siType
def scriptId

// ***** SCRIPT START *****
currentType = CacheAdmin.getEnvironment().getType("NEWSLETTER_SUBSCRIBER")

scriptCode = """content.setValue("/CODE", new com.flexive.shared.value.FxString(false, org.apache.commons.lang.RandomStringUtils.randomAlphanumeric(20).toUpperCase()))"""

if(scriptOverride && CacheAdmin.getEnvironment().scriptExists("SubscriberCode.groovy")) {
	scriptId = CacheAdmin.getEnvironment().getScript("SubscriberCode.groovy").getId()
	EJBLookup.getScriptingEngine().updateScriptCode(scriptId, scriptCode)
} else {
    def scriptInfo = new FxScriptInfo(-1, FxScriptEvent.BeforeContentCreate, "SubscriberCode.groovy", "Create a subscriber code", true, false).asEditable()
    scriptInfo.setCode(scriptCode)
	siType = EJBLookup.getScriptingEngine().createScript(scriptInfo)
    scriptId = siType.id
}
try {
  EJBLookup.getScriptingEngine().createTypeScriptMapping(FxScriptEvent.BeforeContentCreate, scriptId, currentType.getId(), true, true)
} catch (FxEntryExistsException e) {
  //ok, exists
}
// ***** SCRIPT END *****

