SET SCHEMA ${SCHEMA};
${OVERWRITE} DROP TABLE IF EXISTS ${TABLE_NAME};

CREATE TABLE ${TABLE_NAME} (
  ID INTEGER UNSIGNED NOT NULL,
  VER SMALLINT(6) NOT NULL,
  LANG SMALLINT UNSIGNED NOT NULL,
  LVL SMALLINT(6) NOT NULL,
  STEP INTEGER UNSIGNED NOT NULL,
  ISMAX_VER BOOLEAN NOT NULL,
  ISLIVE_VER BOOLEAN NOT NULL,
  POSITIONS VARCHAR(1024) NULL,

  ${STRING_TIMES} STRING${INDEX} VARCHAR(1024),
  ${BIGINT_TIMES} BIGINT${INDEX} BIGINT,
  ${DOUBLE_TIMES} DOUBLE${INDEX} DOUBLE,
  ${SELECT_TIMES} SELECT${INDEX} INT UNSIGNED DEFAULT 0,
  ${TEXT_TIMES} TEXT${INDEX} LONGTEXT,

  PRIMARY KEY (ID,VER,LANG,LVL),

  ${SELECT_TIMES} FOREIGN KEY (SELECT${INDEX}) REFERENCES FXS_SELECTLIST_ITEM(ID),

  FOREIGN KEY (STEP) REFERENCES FXS_WF_STEPS(ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY (LANG) REFERENCES FXS_LANG(LANG_CODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
);
COMMENT ON TABLE ${TABLE_NAME} IS 'Flat storage table';

${STRING_TIMES} CREATE INDEX FXI_${TABLE_NAME}_STRING${INDEX}   ON ${TABLE_NAME}(STRING${INDEX});
${BIGINT_TIMES} CREATE INDEX FXI_${TABLE_NAME}_BIGINT${INDEX}   ON ${TABLE_NAME}(BIGINT${INDEX});
${DOUBLE_TIMES} CREATE INDEX FXI_${TABLE_NAME}_DOUBLE${INDEX}   ON ${TABLE_NAME}(DOUBLE${INDEX});
