-- -------------------------
-- Languages
-- -------------------------

CREATE TABLE FXS_LANG (
  LANG_CODE SMALLINT UNSIGNED NOT NULL,
  ISO_CODE VARCHAR(2) NOT NULL,
  INUSE BOOLEAN DEFAULT FALSE COMMENT 'use this language?',
  DISPPOS SMALLINT UNSIGNED COMMENT 'display position',
  PRIMARY KEY(LANG_CODE),
  UNIQUE KEY LANG_ISO_CODE (ISO_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=LATIN1 COMMENT='Language definitions' ROW_FORMAT=FIXED;

CREATE TABLE FXS_LANG_T (
  LANG_CODE SMALLINT UNSIGNED NOT NULL,
  LANG SMALLINT UNSIGNED NOT NULL,
  DESCRIPTION TEXT CHARACTER SET UTF8 NOT NULL,
  UNIQUE KEY LANG_CODE_LANG(LANG_CODE, LANG),
  FOREIGN KEY FK_LANG_ID(LANG_CODE) REFERENCES FXS_LANG(LANG_CODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_LANG_LANG(LANG) REFERENCES FXS_LANG(LANG_CODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=LATIN1 COMMENT='Language definitions' ROW_FORMAT=FIXED;

-- -------------------------
-- MANDATORS
-- -------------------------
CREATE TABLE FXS_MANDATOR (
 ID INTEGER UNSIGNED NOT NULL,
 NAME VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
 METADATA INTEGER UNSIGNED,
 IS_ACTIVE BOOLEAN NOT NULL,
 CREATED_BY INTEGER UNSIGNED NOT NULL,
 CREATED_AT BIGINT UNSIGNED NOT NULL,
 MODIFIED_BY INTEGER UNSIGNED NOT NULL,
 MODIFIED_AT BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(ID),
 UNIQUE UK_MANDATORS_NAME(NAME)
)
ENGINE = InnoDB
DEFAULT CHARSET=LATIN1
COMMENT = 'all available mandators';

-- -------------------------
-- ACCOUNTS
-- -------------------------
CREATE TABLE FXS_ACCOUNTS (
 ID INTEGER UNSIGNED NOT NULL,
 MANDATOR INTEGER UNSIGNED NOT NULL,
 USERNAME VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
 PASSWORD VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
 EMAIL VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
 CONTACT_ID INTEGER UNSIGNED,
 VALID_FROM BIGINT UNSIGNED,
 VALID_TO BIGINT UNSIGNED,
 DESCRIPTION VARCHAR(2000) CHARACTER SET UTF8 DEFAULT '',
 CREATED_BY INTEGER UNSIGNED NOT NULL,
 CREATED_AT BIGINT UNSIGNED NOT NULL,
 MODIFIED_BY INTEGER UNSIGNED NOT NULL,
 MODIFIED_AT BIGINT UNSIGNED NOT NULL,
 IS_ACTIVE BOOLEAN NOT NULL,
 IS_VALIDATED BOOLEAN NOT NULL,
 LANG SMALLINT UNSIGNED NOT NULL DEFAULT 1,
 LOGIN_NAME VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
 ALLOW_MULTILOGIN BOOLEAN NOT NULL,
 DEFAULT_NODE INTEGER UNSIGNED,
 UPDATETOKEN VARCHAR(64) NULL,
 PRIMARY KEY(ID),
 INDEX IDX_ACCOUNTS_USERNAME(USERNAME),
 INDEX IDX_ACCOUNTS_EMAIL(EMAIL),
 UNIQUE UK_ACCOUNTS_LOGIN_NAME(USERNAME),
 FOREIGN KEY FK_ACCOUNTS_MANDATOR(MANDATOR) REFERENCES FXS_MANDATOR(ID)
   ON DELETE RESTRICT ON UPDATE RESTRICT,
 FOREIGN KEY FK_LANG(LANG) REFERENCES FXS_LANG(LANG_CODE)
    ON DELETE RESTRICT ON UPDATE RESTRICT,
 FOREIGN KEY FK_ACCOUNT_MANDATOR(MANDATOR) REFERENCES FXS_MANDATOR(ID)
   ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET=LATIN1
COMMENT = 'accounts';

-- -------------------------
-- ACCOUNTS DETAILS
-- -------------------------
CREATE TABLE FXS_ACCOUNT_DETAILS (
 ID INTEGER UNSIGNED NOT NULL  ,
 APPLICATION VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
 LAST_LOGIN BIGINT UNSIGNED NOT NULL,
 LAST_LOGIN_FROM VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
 ISLOGGEDIN BOOLEAN NOT NULL,
 FAILED_ATTEMPTS INTEGER UNSIGNED NOT NULL,
 AUTHSRC VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
 PRIMARY KEY(ID,APPLICATION),
 FOREIGN KEY FK_ACCOUNTDETAILS_ID(ID) REFERENCES FXS_ACCOUNTS(ID)
   ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET=LATIN1
COMMENT = 'accounts details, storing the (last) login state';

-- -------------------------
-- GROUPS
-- -------------------------
CREATE TABLE FXS_USERGROUPS (
 ID INTEGER UNSIGNED NOT NULL,
 MANDATOR INTEGER UNSIGNED NOT NULL,
 AUTOMANDATOR INTEGER UNSIGNED,
 ISSYSTEM BOOLEAN NOT NULL DEFAULT FALSE,
 NAME VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
 COLOR VARCHAR(32) NOT NULL DEFAULT '000000',
 CREATED_BY INTEGER UNSIGNED NOT NULL,
 CREATED_AT BIGINT UNSIGNED NOT NULL,
 MODIFIED_BY INTEGER UNSIGNED NOT NULL,
 MODIFIED_AT BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(ID),
 UNIQUE UK_USERGROUPS_NAME(NAME,MANDATOR),
 FOREIGN KEY FK_USERGROUPS_MANDATOR(MANDATOR) REFERENCES FXS_MANDATOR(ID)
   ON DELETE RESTRICT ON UPDATE RESTRICT,
 FOREIGN KEY FK_USERGROUPS_AUTOMANDATOR(AUTOMANDATOR) REFERENCES FXS_MANDATOR(ID)
   ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = InnoDB
COMMENT = 'groups';

-- -------------------------
-- GROUPS to ACCOUNTS
-- -------------------------
CREATE TABLE FXS_USERGROUPMEMBERS (
 ACCOUNT INTEGER UNSIGNED NOT NULL  ,
 USERGROUP INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY(ACCOUNT,USERGROUP),
 FOREIGN KEY FK_USERGROUPMEMBERS_ACCID(ACCOUNT) REFERENCES FXS_ACCOUNTS(ID)
   ON DELETE RESTRICT ON UPDATE RESTRICT,
 FOREIGN KEY FK_USERGROUPMEMBERS_UGID(USERGROUP) REFERENCES FXS_USERGROUPS(ID)
   ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET=LATIN1
COMMENT = 'Groups to accounts relation';

-- -------------------------
-- ACLS
-- -------------------------
CREATE TABLE FXS_ACL (
 ID INTEGER UNSIGNED NOT NULL,
 MANDATOR INTEGER UNSIGNED NOT NULL,
 NAME VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
 DESCRIPTION VARCHAR(255) CHARACTER SET UTF8,
 CAT_TYPE INTEGER NOT NULL COMMENT '1=Content, 2=Structure, 3=Workflow',
 COLOR VARCHAR(32)  DEFAULT '000000',
 CREATED_BY INTEGER UNSIGNED NOT NULL,
 CREATED_AT BIGINT UNSIGNED NOT NULL,
 MODIFIED_BY INTEGER UNSIGNED NOT NULL,
 MODIFIED_AT BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(ID),
 FOREIGN KEY FK_ACL_MANDATOR(MANDATOR) REFERENCES FXS_MANDATOR(ID)
   ON DELETE RESTRICT ON UPDATE RESTRICT,
 UNIQUE KEY UK_ACL_NAME(NAME)
)
ENGINE = InnoDB
DEFAULT CHARSET=LATIN1
COMMENT = 'ACLs'
ROW_FORMAT=FIXED;

CREATE TABLE FXS_ACL_T (
  ID INTEGER UNSIGNED NOT NULL,
  LANG SMALLINT UNSIGNED,
  DEFLANG BOOLEAN,
  LABEL TEXT,
  FOREIGN KEY FK_ACL_LANG(LANG) REFERENCES FXS_LANG(LANG_CODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_ACL_ID(ID) REFERENCES FXS_ACL(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET=UTF8
COMMENT='ACL translations'
ROW_FORMAT=FIXED;

-- -------------------------
-- Role Assignments
-- -------------------------
CREATE TABLE FXS_ROLEMAPPING (
  ACCOUNT INTEGER UNSIGNED NOT NULL,
  USERGROUP INTEGER UNSIGNED NOT NULL,
  ROLE INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(ACCOUNT,USERGROUP,ROLE),
  FOREIGN KEY FK_RO_ACCOUNT(ACCOUNT) REFERENCES FXS_ACCOUNTS(ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_RO_GROUP(USERGROUP) REFERENCES FXS_USERGROUPS(ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET = LATIN1
COMMENT = 'Role assignments';

CREATE TABLE FXS_HISTORY(
  ACCOUNT INTEGER UNSIGNED NOT NULL,
  LOGINNAME VARCHAR(512) NOT NULL,
  TIMESTP BIGINT UNSIGNED NOT NULL,
  ACTION_KEY VARCHAR(512) NOT NULL,
  ACTION_ARGS VARCHAR(4096) COMMENT 'key arguments, separated by pipe characters',
  SESSION VARCHAR(256),
  APPLICATION VARCHAR(256),
  REMOTEHOST VARCHAR(256),
  TYPEID INTEGER UNSIGNED,
  TYPENAME VARCHAR(256),
  PKID INTEGER UNSIGNED,
  PKVER SMALLINT UNSIGNED,
  EN_MESSAGE LONGTEXT NOT NULL,
  DATA LONGTEXT
)
ENGINE = InnoDB
DEFAULT CHARSET = UTF8
COMMENT = 'History tracker';


-- -------------------------
-- ACL Assignments
-- -------------------------
CREATE TABLE FXS_ACLASSIGNMENTS(
  USERGROUP INTEGER UNSIGNED NOT NULL,
  ACL INTEGER UNSIGNED NOT NULL,
  PEDIT BOOLEAN NOT NULL,
  PREMOVE BOOLEAN NOT NULL,
  PEXPORT BOOLEAN NOT NULL,
  PREL BOOLEAN NOT NULL,
  PREAD BOOLEAN NOT NULL,
  PCREATE BOOLEAN NOT NULL,
  CREATED_BY INTEGER UNSIGNED NOT NULL,
  CREATED_AT BIGINT UNSIGNED NOT NULL,
  MODIFIED_BY INTEGER UNSIGNED NOT NULL,
  MODIFIED_AT BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY(USERGROUP,ACL),
  FOREIGN KEY FK_ACLUG_GROUP(USERGROUP) REFERENCES FXS_USERGROUPS(ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_ACLUG_ACL(ACL) REFERENCES FXS_ACL(ID)
	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET = LATIN1
COMMENT = 'ACL assignments';


-- -------------------------
-- Workflows
-- -------------------------
CREATE TABLE FXS_WORKFLOWS(
  ID INTEGER UNSIGNED NOT NULL,
  NAME VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
  DESCRIPTION VARCHAR(1024) CHARACTER SET UTF8,
  PRIMARY KEY(ID),
  UNIQUE KEY UK_WORKFLOWS_NAME(NAME)
)
ENGINE = InnoDB
COMMENT = 'Workflows';

-- -------------------------
-- Step Definitions
-- -------------------------
CREATE TABLE FXS_WF_STEPDEFS (
  ID INTEGER UNSIGNED NOT NULL,
  NAME VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
  UNIQUE_TARGET INTEGER UNSIGNED,
  PRIMARY KEY(ID),
  UNIQUE KEY UK_STEPDEFS_NAME(NAME),
  FOREIGN KEY FK_STEPDEFS_TARGET(UNIQUE_TARGET) REFERENCES FXS_WF_STEPDEFS(ID)
	  ON DELETE SET NULL
)
ENGINE = InnoDB
DEFAULT CHARSET = LATIN1
COMMENT = 'Step Templates';

-- -------------------------
-- Step Definitions Translations
-- -------------------------
CREATE TABLE FXS_WF_STEPDEFS_T (
  ID INTEGER UNSIGNED NOT NULL,
  LANG SMALLINT UNSIGNED NOT NULL,
  DEFLANG BOOLEAN,
  NAME VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
  PRIMARY KEY(LANG,ID),
  FOREIGN KEY FK_FSTEPDEFS_ID(ID) REFERENCES FXS_WF_STEPDEFS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_FSTEPDEFS_LANG(LANG) REFERENCES FXS_LANG(LANG_CODE)
	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET = LATIN1
COMMENT = 'Step Templates Translation';


-- -------------------------
-- Steps
-- -------------------------
CREATE TABLE FXS_WF_STEPS (
  ID INTEGER UNSIGNED NOT NULL,
  STEPDEF INTEGER UNSIGNED NOT NULL,
  WORKFLOW INTEGER UNSIGNED NOT NULL,
  ACL INTEGER UNSIGNED NOT NULL ,
  PRIMARY KEY(ID),
  UNIQUE KEY UK_DEF_WF (STEPDEF, WORKFLOW),
  FOREIGN KEY STEPS_FK_STEPDEF(STEPDEF) REFERENCES FXS_WF_STEPDEFS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY STEPS_FK_WORKFLOW(WORKFLOW) REFERENCES FXS_WORKFLOWS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY STEPS_FK_ACL(ACL) REFERENCES FXS_ACL(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET = LATIN1
COMMENT = 'Steps';

-- -------------------------
-- Step routes
-- -------------------------
CREATE TABLE FXS_WF_ROUTES (
  ID INTEGER UNSIGNED NOT NULL,
  FROM_STEP INTEGER UNSIGNED NOT NULL,
  TO_STEP INTEGER UNSIGNED NOT NULL,
  USERGROUP INTEGER UNSIGNED NOT NULL ,
  PRIMARY KEY(ID),
  UNIQUE KEY UK_ROUTE(FROM_STEP, TO_STEP, USERGROUP) ,
  FOREIGN KEY FK_ROUTE_GROUP(USERGROUP) REFERENCES FXS_USERGROUPS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_ROUTE_FROM_STEP(FROM_STEP) REFERENCES FXS_WF_STEPS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_ROUTE_TO_STEP(TO_STEP) REFERENCES FXS_WF_STEPS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET = LATIN1
COMMENT = 'Routes';


-- -------------------------
-- Content Type Definitions
-- -------------------------

CREATE TABLE FXS_TYPEDEF (
  ID INTEGER UNSIGNED NOT NULL,
  ACL INTEGER UNSIGNED NOT NULL COMMENT 'ACL for the type, only checked if enabled in permissions',
  WORKFLOW INTEGER UNSIGNED NOT NULL,
  NAME VARCHAR(255) CHARACTER SET UTF8 NOT NULL COMMENT 'name of the type',
  PARENT INTEGER UNSIGNED DEFAULT NULL COMMENT 'parent for derived types, null if this is the parent, cyclic checks have to be performed by the application',
  STORAGE_MODE tinyint(4) unsigned NOT NULL COMMENT 'how are data tables organized \n0=inbound\n1=outbound\n2=external table (no versioning, permissions, etc)\n3=memory (nothing persisted, for small amounts of data only, no query engine available!)',
  CATEGORY tinyint(4) unsigned NOT NULL COMMENT '0=system,  1=user',
  TYPE_MODE tinyint(4) unsigned NOT NULL COMMENT '0=Content, 1=Relation',
  LANG_MODE tinyint(4) unsigned NOT NULL COMMENT '0=no multi language, 1=one language per instance, 2=multiple languages per field',
  TYPE_STATE tinyint(4) unsigned NOT NULL COMMENT '0=available, 1=temporary unavailable, 2=permanently unavailable\ntables can be unavailable if structural changes resulted in errors and manual intervention is needed',
  SECURITY_MODE tinyint(4) unsigned NOT NULL COMMENT 'Bit coded field that indicates which permissions are used. 0=none, 0x01=instance, 0x02=property, 0x04=step, 0x08=type',
  TRACKHISTORY BOOLEAN NOT NULL COMMENT 'track changes on instance data? HISTORY_AGE tells for how long they are kept.',
  HISTORY_AGE INTEGER UNSIGNED COMMENT 'Days to keep histories for instance changes if TRACKHISTORY is true. 0=for ever',
  MAX_VERSIONS INTEGER NOT NULL COMMENT 'maximum number of versions to keep (if the storage mode supports versions)\n-1 = unlimited\n0 = no versioning\n> 0 = number of versions to keep',
  REL_TOTAL_MAXSRC INTEGER UNSIGNED NOT NULL COMMENT 'If not 0 used to override the MAXSRC from FXS_TYPERELS for a total amount',
  REL_TOTAL_MAXDST INTEGER UNSIGNED NOT NULL COMMENT 'If not 0 used to override the MAXDST from FXS_TYPERELS for a total amount',
  ICON_REF INTEGER UNSIGNED COMMENT 'Optional reference to a content instance for a preview icon',
  CREATED_BY INTEGER UNSIGNED NOT NULL,
  CREATED_AT BIGINT UNSIGNED NOT NULL,
  MODIFIED_BY INTEGER UNSIGNED DEFAULT NULL,
  MODIFIED_AT BIGINT UNSIGNED,
  PRIMARY KEY  (ID),
  UNIQUE KEY UK_TYPENAME(NAME),
  FOREIGN KEY FK_TYPEDEF_PARENT(PARENT) REFERENCES FXS_TYPEDEF(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_TYPEDEF_ACL(ACL) REFERENCES FXS_ACL(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_TYPEDEF_WORKFLOW(WORKFLOW) REFERENCES FXS_WORKFLOWS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET = LATIN1
COMMENT='Type definitions'
ROW_FORMAT=FIXED;

CREATE TABLE FXS_TYPEDEF_T (
  ID INTEGER UNSIGNED NOT NULL,
  LANG SMALLINT UNSIGNED,
  DEFLANG BOOLEAN,
  DESCRIPTION TEXT CHARACTER SET UTF8,
  FOREIGN KEY FK_TYPEDEF_LANG(LANG) REFERENCES FXS_LANG(LANG_CODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_TYPEDEF_ID(ID) REFERENCES FXS_TYPEDEF(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET = LATIN1
COMMENT='Type definition translations'
ROW_FORMAT=FIXED;

CREATE TABLE FXS_TYPERELS (
  TYPEDEF INTEGER UNSIGNED NOT NULL,
  TYPESRC INTEGER UNSIGNED NOT NULL,
  TYPEDST INTEGER UNSIGNED NOT NULL,
  MAXSRC INTEGER UNSIGNED NOT NULL COMMENT 'Max. number of allowed source entries, unlimited if 0',
  MAXDST INTEGER UNSIGNED NOT NULL COMMENT 'Max. number of allowed destination entries, unlimited if 0',
  UNIQUE KEY UK_TYPEREFS(TYPEDEF,TYPESRC,TYPEDST),
  FOREIGN KEY FK_TYPERELS_DEF(TYPEDEF) REFERENCES FXS_TYPEDEF(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_TYPERELS_SRC(TYPESRC) REFERENCES FXS_TYPEDEF(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_TYPERELS_DST(TYPEDST) REFERENCES FXS_TYPEDEF(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET = LATIN1
COMMENT='Possible relation definitions'
ROW_FORMAT=FIXED;

-- -------------------------
-- Property Groups Definition
-- -------------------------
CREATE TABLE FXS_TYPEGROUPS (
  ID INTEGER UNSIGNED NOT NULL,
  NAME VARCHAR(50) CHARACTER SET UTF8 NOT NULL,
  DEFMINMULT INTEGER NOT NULL,
  DEFMAXMULT INTEGER NOT NULL,
  MAYOVERRIDEMULT BOOLEAN NOT NULL,
  PRIMARY KEY  (ID)
)
ENGINE=InnoDB
DEFAULT CHARSET = LATIN1
COMMENT='Groups'
ROW_FORMAT=FIXED;

CREATE TABLE FXS_TYPEGROUPS_T (
  ID INTEGER UNSIGNED NOT NULL,
  LANG SMALLINT UNSIGNED,
  DESCRIPTION TEXT CHARACTER SET UTF8,
  HINT TEXT CHARACTER SET UTF8,
  FOREIGN KEY FK_TYPEGROUPS_LANG(LANG) REFERENCES FXS_LANG(LANG_CODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_TYPEGROUPS_ID(ID) REFERENCES FXS_TYPEGROUPS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET = LATIN1
COMMENT='Groups translations'
ROW_FORMAT=FIXED;

-- -------------------------
-- Property Datatype Definition
-- -------------------------
CREATE TABLE FXS_DATATYPES (
  TYPECODE INTEGER UNSIGNED NOT NULL,
  NAME VARCHAR(50) CHARACTER SET UTF8 NOT NULL,
  PRIMARY KEY  (TYPECODE),
  UNIQUE KEY UK_NAME(NAME)
)
ENGINE=InnoDB
DEFAULT CHARSET = LATIN1
ROW_FORMAT=FIXED
COMMENT='Datatypes';

CREATE TABLE FXS_DATATYPES_T (
  ID INTEGER UNSIGNED NOT NULL,
  LANG SMALLINT UNSIGNED,
  DEFLANG BOOLEAN,
  DESCRIPTION TEXT CHARACTER SET UTF8,
  FOREIGN KEY FK_DATATYPES_LANG(LANG) REFERENCES FXS_LANG(LANG_CODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_DATATYPES_ID(ID) REFERENCES FXS_DATATYPES(TYPECODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET = LATIN1
COMMENT='Datatypes translations'
ROW_FORMAT=FIXED;

-- -------------------------
-- Binary storage
-- -------------------------

CREATE TABLE FX_BINARY (
  ID INTEGER NOT NULL,
  VER SMALLINT(6) NOT NULL,
  QUALITY SMALLINT UNSIGNED NOT NULL,
  FBLOB LONGBLOB NOT NULL,
  NAME VARCHAR(1025) CHARACTER SET UTF8 NOT NULL,
  BLOBSIZE INTEGER UNSIGNED NOT NULL,
  XMLMETA LONGTEXT CHARACTER SET UTF8 COMMENT 'XML Meta Data like IPTC',
  CREATED_AT BIGINT UNSIGNED NOT NULL,
  MIMETYPE VARCHAR(50) NOT NULL,
  PREVIEW_REF INTEGER DEFAULT NULL,
  ISIMAGE BOOLEAN NOT NULL,
  RESOLUTION DOUBLE,
  WIDTH INTEGER UNSIGNED,
  HEIGHT INTEGER UNSIGNED,
  PREV1 LONGBLOB COMMENT 'if image: scaled to fit a 42x42 box, else null',
  PREV2 LONGBLOB COMMENT 'if image: scaled to fit a 85x85 box, else null',
  PREV3 LONGBLOB COMMENT 'if image: scaled to fit a 232x232 box, else null',
  PREV1_WIDTH INTEGER UNSIGNED,
  PREV1_HEIGHT INTEGER UNSIGNED,
  PREV2_WIDTH INTEGER UNSIGNED,
  PREV2_HEIGHT INTEGER UNSIGNED,
  PREV3_WIDTH INTEGER UNSIGNED,
  PREV3_HEIGHT INTEGER UNSIGNED,
  PREV1SIZE INTEGER UNSIGNED,
  PREV2SIZE INTEGER UNSIGNED,
  PREV3SIZE INTEGER UNSIGNED,
  PRIMARY KEY (ID, VER, QUALITY),
  FOREIGN KEY FK_PREVIEW_REF(PREVIEW_REF) REFERENCES FX_BINARY(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET=LATIN1
ROW_FORMAT=COMPRESSED;

CREATE INDEX FXI_BINARY_ID ON FX_BINARY(ID);
CREATE INDEX FXI_BINARY_VER ON FX_BINARY(VER);
CREATE INDEX FXI_BINARY_MIME ON FX_BINARY(MIMETYPE);

-- -------------------------
-- Selectlists
-- -------------------------

CREATE TABLE FXS_SELECTLIST (
  ID INTEGER UNSIGNED NOT NULL,
  PARENTID INTEGER UNSIGNED,
  NAME VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
  ALLOW_ITEM_CREATE BOOLEAN NOT NULL,
  ACL_CREATE_ITEM INTEGER UNSIGNED NOT NULL,
  ACL_ITEM_NEW INTEGER UNSIGNED NOT NULL,
  DEFAULT_ITEM INTEGER UNSIGNED,
  PRIMARY KEY (ID),
  UNIQUE KEY UK_NAME(NAME),
  FOREIGN KEY FK_SELECTLIST_PARENTID(PARENTID) REFERENCES FXS_SELECTLIST(ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_SELECTLIST_CREATE_ACL(ACL_CREATE_ITEM) REFERENCES FXS_ACL(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_SELECTLIST_NEW_ACL(ACL_ITEM_NEW) REFERENCES FXS_ACL(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET=LATIN1
ROW_FORMAT=COMPRESSED;

CREATE TABLE FXS_SELECTLIST_T (
  ID INTEGER UNSIGNED NOT NULL,
  LANG SMALLINT UNSIGNED NOT NULL,
  LABEL TEXT CHARACTER SET UTF8 COMMENT 'Label for GUIs',
  DESCRIPTION TEXT CHARACTER SET UTF8 COMMENT 'Description',
  PRIMARY KEY (ID,LANG),
  FOREIGN KEY FK_SELECTLIST_LANG(LANG) REFERENCES FXS_LANG(LANG_CODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_SELECTLIST_ID(ID) REFERENCES FXS_SELECTLIST(ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET = LATIN1
COMMENT='Selectlist translations'
ROW_FORMAT=FIXED;

CREATE TABLE FXS_SELECTLIST_ITEM (
  ID INTEGER UNSIGNED NOT NULL,
  ACL INTEGER UNSIGNED NOT NULL,
  PARENTID INTEGER UNSIGNED,
  LISTID INTEGER UNSIGNED NOT NULL,
  NAME VARCHAR(255) CHARACTER SET UTF8,
  DATA TEXT CHARACTER SET UTF8,
  COLOR VARCHAR(32) NOT NULL DEFAULT '000000',
  CREATED_BY INTEGER UNSIGNED NOT NULL,
  CREATED_AT BIGINT UNSIGNED NOT NULL,
  MODIFIED_BY INTEGER UNSIGNED NOT NULL,
  MODIFIED_AT BIGINT UNSIGNED NOT NULL,
  DBIN_ID INTEGER,
  DBIN_VER SMALLINT(6),
  DBIN_QUALITY SMALLINT UNSIGNED,
  PRIMARY KEY (ID),
  UNIQUE KEY UK_SELECTLIST_ITEM(LISTID,NAME),
  FOREIGN KEY FK_SELECTLIST_ITEM_ID(LISTID) REFERENCES FXS_SELECTLIST(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_SELECTLIST_ITEM_ACL(ACL) REFERENCES FXS_ACL(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_SELECTLIST_ITEM__DBIN(DBIN_ID,DBIN_VER,DBIN_QUALITY) REFERENCES FX_BINARY(ID,VER,QUALITY)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_SELECTLIST_ITEM__PARENTID(PARENTID) REFERENCES FXS_SELECTLIST_ITEM(ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET=LATIN1
ROW_FORMAT=COMPRESSED;

CREATE TABLE FXS_SELECTLIST_ITEM_T (
  ID INTEGER UNSIGNED NOT NULL,
  LANG SMALLINT UNSIGNED NOT NULL,
  DEFLANG BOOLEAN,
  LABEL VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
  PRIMARY KEY(LANG,ID),
  FOREIGN KEY FK_SELECTLIST_ITEM_ID(ID) REFERENCES FXS_SELECTLIST_ITEM(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_FSTEPDEFS_LANG(LANG) REFERENCES FXS_LANG(LANG_CODE)
	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET = LATIN1
COMMENT = 'Selectlist item translations';

ALTER TABLE FXS_SELECTLIST ADD FOREIGN KEY FK_SELECTLIST_DEFAULT_ITEM(DEFAULT_ITEM) REFERENCES FXS_SELECTLIST_ITEM(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT;

-- -------------------------
-- Property Definition
-- -------------------------
CREATE TABLE FXS_TYPEPROPS (
  ID INTEGER UNSIGNED NOT NULL,
  SYSINTERNAL BOOLEAN NOT NULL DEFAULT FALSE,
  NAME VARCHAR(50) CHARACTER SET UTF8 NOT NULL,
  DEFMINMULT INTEGER UNSIGNED NOT NULL,
  DEFMAXMULT INTEGER UNSIGNED NOT NULL,
  MAYOVERRIDEMULT BOOLEAN NOT NULL COMMENT 'if true, assignments of this property may override the multiplicity',
  ACL INTEGER UNSIGNED NOT NULL,
  MAYOVERRIDEACL BOOLEAN NOT NULL COMMENT 'if true, assignments of this property may override the ACL',
  DATATYPE INTEGER UNSIGNED NOT NULL COMMENT 'Data type like integer, string, numeric, etc.',
  REFTYPE INTEGER UNSIGNED COMMENT 'For referenced data types the referenced type',
  REFLIST INTEGER UNSIGNED COMMENT 'For select list data types the referenced select list',
  ISFULLTEXTINDEXED BOOLEAN NOT NULL COMMENT 'For MySQL: copy value to a MyISAM table for fulltext queries',
  UNIQUEMODE SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  DEFAULT_VALUE TEXT CHARACTER SET UTF8 COMMENT 'Default value serialized to XML',
  PRIMARY KEY PK_TYPEPROPS_ID(ID),
  UNIQUE KEY UK_TYPEPROPS_NAME(NAME),
  FOREIGN KEY FK_DATATYPE(DATATYPE) REFERENCES FXS_DATATYPES(TYPECODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_REFTYPE(REFTYPE) REFERENCES FXS_TYPEDEF(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_REFLIST(REFLIST) REFERENCES FXS_SELECTLIST(ID)
   	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_PROP_ACL(ACL) REFERENCES FXS_ACL(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT  	
)
ENGINE=InnoDB
DEFAULT CHARSET = LATIN1
ROW_FORMAT=FIXED
COMMENT='Properties';

CREATE TABLE FXS_TYPEPROPS_T (
  ID INTEGER UNSIGNED NOT NULL,
  LANG SMALLINT UNSIGNED NOT NULL,
  DESCRIPTION TEXT CHARACTER SET UTF8 COMMENT 'Description',
  HINT TEXT CHARACTER SET UTF8 COMMENT 'Hint messages for GUIs',
  PRIMARY KEY (ID,LANG),
  FOREIGN KEY FK_TYPEPROPS_LANG(LANG) REFERENCES FXS_LANG(LANG_CODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_TYPEPROPS_ID(ID) REFERENCES FXS_TYPEPROPS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET = LATIN1
COMMENT='Properties translations'
ROW_FORMAT=FIXED;


-- -------------------------
-- Sort order for Properties/Groups
-- -------------------------
/*
special handling for positioning because types can be derived.
this might not be the best solution because of possible inconsistencies but feel free to come up with a better one ;)

groups belong to types, but types can be inherited from other types (simple inheritance, though over multiple hierarchy depths!), thus we need
a way to position groups and properties.
groups are directly attached to types and properties directly to groups.
it would be sufficient to just store the referenced typedef with the group but due to inheritance it is possible that an inherited type
'extends' a group from a parent type with a new property.
consider the following:
Type: A
Group: MAIN
Property: P
The property is defined yb the path A.MAIN.P
If you want to introduce a new Type, named 'B' who is derived from A but has an additional Property PB that should be attached to the
(derived) group MAIN there is (to my knowledge) no other way for a working positioning than the one used here,
*/

CREATE TABLE FXS_ASSIGNMENTS (
  ID INTEGER UNSIGNED NOT NULL COMMENT 'Id of this assignment',
  ATYPE SMALLINT UNSIGNED NOT NULL COMMENT 'Group (0) or Property (1) assignment',
  ENABLED BOOLEAN NOT NULL COMMENT 'Is this assignment available?',
  TYPEDEF INTEGER UNSIGNED NOT NULL COMMENT 'FxType this assignment belongs to',
  MINMULT INTEGER UNSIGNED NOT NULL,
  MAXMULT INTEGER UNSIGNED NOT NULL,
  DEFMULT INTEGER UNSIGNED NOT NULL COMMENT 'Default multiplicity',
  POS SMALLINT UNSIGNED NOT NULL,
  XPATH VARCHAR(512) NOT NULL,
  XALIAS VARCHAR(50),
  BASE INTEGER UNSIGNED COMMENT 'if assigned to a derived type BASE references the same assignment in a parent type, else the assignment to root; if its a root assignment it is 0',
  PARENTGROUP INTEGER UNSIGNED NOT NULL COMMENT 'if not 0 the PARENTGROUP is the assignment of the parent group, else it is assigned to the root',
-- Group (ATYPE==0) fields:
  AGROUP INTEGER UNSIGNED COMMENT 'assigned group',
  GROUPMODE SMALLINT UNSIGNED COMMENT '0=any-of, 1=one-of',
-- Property (ATYPE==1) fields:
  APROPERTY INTEGER UNSIGNED COMMENT 'assigned property',
  ACL INTEGER UNSIGNED,
  DEFLANG SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Default language if multilingual, 0 (system) if no default set',
  SYSINTERNAL BOOLEAN NOT NULL DEFAULT FALSE,
  DEFAULT_VALUE TEXT CHARACTER SET UTF8 COMMENT 'Default value serialized to XML',
  PRIMARY KEY (ID),
  UNIQUE KEY UK_PROPPOSITIONING(TYPEDEF,POS,PARENTGROUP),
  UNIQUE KEY UK_ASSIGNMENTS(TYPEDEF,PARENTGROUP,XALIAS),
  FOREIGN KEY FK_TYPEDEF_ID(TYPEDEF) REFERENCES FXS_TYPEDEF(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_PARENTGROUP_ID(PARENTGROUP) REFERENCES FXS_ASSIGNMENTS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_BASE_ID(BASE) REFERENCES FXS_ASSIGNMENTS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_GROUP_ID(AGROUP) REFERENCES FXS_TYPEGROUPS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_PROPERTY_ID(APROPERTY) REFERENCES FXS_TYPEPROPS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_DEFLANG_ID(DEFLANG) REFERENCES FXS_LANG(LANG_CODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_ASS_ACL(ACL) REFERENCES FXS_ACL(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT 
)
ENGINE=InnoDB
DEFAULT CHARSET = LATIN1
COMMENT='Assignment of properties and groups to types/relations'
ROW_FORMAT=FIXED;

CREATE TABLE FXS_ASSIGNMENTS_T (
  ID INTEGER UNSIGNED NOT NULL,
  LANG SMALLINT UNSIGNED NOT NULL,
  DESCRIPTION TEXT CHARACTER SET UTF8 COMMENT 'Description',
  HINT TEXT CHARACTER SET UTF8 COMMENT 'Hint messages for GUIs',
  PRIMARY KEY (ID,LANG),
  FOREIGN KEY FK_TYPEPROPS_LANG(LANG) REFERENCES FXS_LANG(LANG_CODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_ASSIGNMENT_ID(ID) REFERENCES FXS_ASSIGNMENTS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET = LATIN1
COMMENT='Assignments translations'
ROW_FORMAT=FIXED;

-- -------------------------
-- Property/Assignment Options
-- -------------------------
CREATE TABLE FXS_PROP_OPT (
  OPTKEY VARCHAR(32),
  ID INTEGER UNSIGNED NOT NULL,
  ASSID INTEGER UNSIGNED,
  MAYOVERRIDE BOOLEAN,
  OPTVALUE TEXT,
  FOREIGN KEY FK_PROPERTY_ID(ID) REFERENCES FXS_TYPEPROPS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_ASSIGNMENT_ID(ASSID) REFERENCES FXS_ASSIGNMENTS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET = LATIN1
COMMENT = 'Options for properties/assignments';

-- -------------------------
-- Group/Assignment Options
-- -------------------------
CREATE TABLE FXS_GROUP_OPT (
  OPTKEY VARCHAR(32),
  ID INTEGER UNSIGNED NOT NULL,
  ASSID INTEGER UNSIGNED,
  MAYOVERRIDE BOOLEAN,
  OPTVALUE TEXT,
  FOREIGN KEY FK_GROUP_ID(ID) REFERENCES FXS_TYPEGROUPS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET = LATIN1
COMMENT = 'Options for groups/assignments';

-- -------------------------
-- Main content data
-- -------------------------
CREATE TABLE FX_CONTENT (
  ID INTEGER UNSIGNED NOT NULL,
  VER SMALLINT(6) NOT NULL,
  REFID INTEGER UNSIGNED,
  REFVER SMALLINT(6),
  TDEF INTEGER UNSIGNED NOT NULL,
  MANDATOR INTEGER UNSIGNED NOT NULL,
  ACL INTEGER UNSIGNED NOT NULL,
  STEP INTEGER UNSIGNED NOT NULL,
  MAX_VER SMALLINT(6) NOT NULL,
  LIVE_VER SMALLINT(6) NOT NULL,
  ISMAX_VER BOOLEAN NOT NULL,
  ISLIVE_VER BOOLEAN NOT NULL,
  ISACTIVE BOOLEAN NOT NULL,
  MAINLANG SMALLINT UNSIGNED NOT NULL,
  RELSRC_ID INTEGER UNSIGNED,
  RELSRC_VER SMALLINT(6),
  RELDST_ID INTEGER UNSIGNED,
  RELDST_VER SMALLINT(6),
  RELSRC_POS INTEGER UNSIGNED,
  RELDST_POS INTEGER UNSIGNED,
  CREATED_BY INTEGER UNSIGNED NOT NULL,
  CREATED_AT BIGINT UNSIGNED NOT NULL,
  MODIFIED_BY INTEGER UNSIGNED NOT NULL,
  MODIFIED_AT BIGINT UNSIGNED NOT NULL,
  DBIN_ID INTEGER NOT NULL,
  DBIN_VER SMALLINT(6) NOT NULL,
  DBIN_QUALITY SMALLINT UNSIGNED NOT NULL,
  DBIN_ACL INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY  (ID,VER),
  FOREIGN KEY FK_CONTENT_LANG(MAINLANG) REFERENCES FXS_LANG(LANG_CODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_CONTENT_TDEF(TDEF) REFERENCES FXS_TYPEDEF(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_CONTENT_MANDATOR(MANDATOR) REFERENCES FXS_MANDATOR(ID)
   ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_CONTENT_STEP(STEP) REFERENCES FXS_WF_STEPS(ID)
   ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_CONTENT_ACL(ACL) REFERENCES FXS_ACL(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_CONTENT_DBIN(DBIN_ID,DBIN_VER,DBIN_QUALITY) REFERENCES FX_BINARY(ID,VER,QUALITY)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_CONTENT_DBIN_ACL(DBIN_ACL) REFERENCES FXS_ACL(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET = LATIN1
ROW_FORMAT=FIXED;

CREATE INDEX FXI_CONTENT_ID ON FX_CONTENT(ID);
CREATE INDEX FXI_CONTENT_VER ON FX_CONTENT(VER);
CREATE INDEX FXI_CONTENT_REFID ON FX_CONTENT(REFID);
CREATE INDEX FXI_CONTENT_REFVER ON FX_CONTENT(REFVER);
CREATE INDEX FXI_CONTENT_TDEF ON FX_CONTENT(TDEF);
CREATE INDEX FXI_CONTENT_ACL ON FX_CONTENT(ACL);
CREATE INDEX FXI_CONTENT_STEP ON FX_CONTENT(STEP);
CREATE INDEX FXI_CONTENT_MANDATOR ON FX_CONTENT(MANDATOR);
CREATE INDEX FXI_CONTENT_MAX_VER ON FX_CONTENT(MAX_VER);
CREATE INDEX FXI_CONTENT_LIVE_VER ON FX_CONTENT(LIVE_VER);
CREATE INDEX FXI_CONTENT_ISMAX_VER ON FX_CONTENT(ISMAX_VER);
CREATE INDEX FXI_CONTENT_ISLIVE_VER ON FX_CONTENT(ISLIVE_VER);
CREATE INDEX FXI_CONTENT_ISACTIVE ON FX_CONTENT(ISACTIVE);
CREATE INDEX FXI_CONTENT_MAINLANG ON FX_CONTENT(MAINLANG);
CREATE INDEX FXI_CONTENT_RELSRC_ID ON FX_CONTENT(RELSRC_ID);
CREATE INDEX FXI_CONTENT_RELSRC_VER ON FX_CONTENT(RELSRC_VER);
CREATE INDEX FXI_CONTENT_RELDST_ID ON FX_CONTENT(RELDST_ID);
CREATE INDEX FXI_CONTENT_RELDST_VER ON FX_CONTENT(RELDST_VER);
CREATE INDEX FXI_CONTENT_RELSRC_POS ON FX_CONTENT(RELSRC_POS);
CREATE INDEX FXI_CONTENT_RELDST_POS ON FX_CONTENT(RELDST_POS);
CREATE INDEX FXI_CONTENT_CREATED_BY ON FX_CONTENT(CREATED_BY);
CREATE INDEX FXI_CONTENT_CREATED_AT ON FX_CONTENT(CREATED_AT);
CREATE INDEX FXI_CONTENT_MODIFIED_BY ON FX_CONTENT(MODIFIED_BY);
CREATE INDEX FXI_CONTENT_MODIFIED_AT ON FX_CONTENT(MODIFIED_AT);


-- -------------------------
-- Binary transit table
-- -------------------------

CREATE TABLE FXS_BINARY_TRANSIT (
	BKEY VARCHAR(32) NOT NULL,
	FBLOB LONGBLOB NOT NULL,
	BLOBSIZE INTEGER UNSIGNED,
	TFER_DONE BOOLEAN COMMENT 'Data still being transferred or finished?',
	EXPIRE BIGINT UNSIGNED NOT NULL,
	PREVIEW_REF INTEGER DEFAULT NULL,
	PREV1 LONGBLOB COMMENT 'if image: scaled to fit a 42x42 box, else null',
    PREV2 LONGBLOB COMMENT 'if image: scaled to fit a 85x85 box, else null',
    PREV3 LONGBLOB COMMENT 'if image: scaled to fit a 232x232 box, else null',
    PREV1_WIDTH INTEGER UNSIGNED,
    PREV1_HEIGHT INTEGER UNSIGNED,
    PREV2_WIDTH INTEGER UNSIGNED,
    PREV2_HEIGHT INTEGER UNSIGNED,
    PREV3_WIDTH INTEGER UNSIGNED,
    PREV3_HEIGHT INTEGER UNSIGNED,
    PREV1SIZE INTEGER UNSIGNED,
    PREV2SIZE INTEGER UNSIGNED,
    PREV3SIZE INTEGER UNSIGNED,
	PRIMARY KEY PK_BINARY_TRANSIT(BKEY),
    FOREIGN KEY FK_PREVIEW_REF(PREVIEW_REF) REFERENCES FX_BINARY(ID)
  	    ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=MyISAM
DEFAULT CHARSET=LATIN1;

CREATE INDEX FXI_BINARY_TR_BKEY ON FXS_BINARY_TRANSIT(BKEY);
CREATE INDEX FXI_BINARY_TR_EXPIRE ON FXS_BINARY_TRANSIT(EXPIRE);

-- -------------------------
-- Content detail data
-- -------------------------

-- select for correct order: select <data fields> from fx_content_data where <bla> order by POS
CREATE TABLE FX_CONTENT_DATA (
  ID INTEGER UNSIGNED NOT NULL,
  VER SMALLINT(6) NOT NULL,
  POS SMALLINT(6) COMMENT 'Positioning relative to current hierarchy level maintained by flexive',
  LANG SMALLINT UNSIGNED NOT NULL,
  TPROP  INTEGER UNSIGNED COMMENT 'FXS_TYPEPROPS id unless its a group',
  ASSIGN INTEGER UNSIGNED NOT NULL COMMENT 'Id of the assignment',
  XDEPTH SMALLINT(6) COMMENT 'XPath hierarchy depth',
  XPATH TEXT NOT NULL,
  XPATHMULT TEXT NOT NULL,
  XMULT VARCHAR(255) NOT NULL COMMENT 'Multiplicities for each element like 1,1,2,5,etc. preceeded by 1 for the root group',
  XINDEX SMALLINT(6) NOT NULL COMMENT 'Multiplicity of this element',
  PARENTXMULT VARCHAR(255) NOT NULL COMMENT 'XMULT of the parent group (needed for unique positioning), always 1 for entries in the root group',
  PARENTXPATH TEXT NOT NULL,
  ISMAX_VER BOOLEAN NOT NULL,
  ISLIVE_VER BOOLEAN NOT NULL,
  ISGROUP BOOLEAN NOT NULL,
  ISMLDEF BOOLEAN NOT NULL COMMENT 'Is this field the multilanguage default?',
  FSELECT INTEGER UNSIGNED DEFAULT 0,
  FREF INTEGER UNSIGNED DEFAULT NULL COMMENT 'Reference to other content instances',
  FDATE1 DATETIME NULL DEFAULT NULL,
  FDATE1_Y INTEGER,
  FDATE1_M SMALLINT,
  FDATE1_D SMALLINT,
  FDATE1_HH SMALLINT,
  FDATE1_MM SMALLINT,
  FDATE1_SS SMALLINT,
  FDATE2 DATETIME NULL DEFAULT NULL,
  FDATE2_Y INTEGER,
  FDATE2_M SMALLINT,
  FDATE2_D SMALLINT,
  FDATE2_HH SMALLINT,
  FDATE2_MM SMALLINT,
  FDATE2_SS SMALLINT,
  FBLOB INTEGER,
  FCLOB LONGTEXT CHARACTER SET UTF8,
  UFCLOB LONGTEXT CHARACTER SET UTF8 COMMENT 'Clob with uppercase values',
  FINT INTEGER COMMENT 'Integer and for references',
  FBIGINT BIGINT,
  FTEXT1024 VARCHAR(1024) CHARACTER SET UTF8,
  UFTEXT1024 VARCHAR(1024) CHARACTER SET UTF8,
  FDOUBLE DOUBLE,
--  FDOUBLE DECIMAL(65,30),
  FFLOAT DOUBLE,
  FBOOL BOOLEAN,
  PRIMARY KEY PK_DATA(ID,VER,LANG,ASSIGN,XMULT,FSELECT),
--  UNIQUE KEY UK_POS (ID,VER,POS,LANG,PARENTXMULT,PARENTXPATH(256),FSELECT),
  FOREIGN KEY FK_CONTENT_DATA_LANG(LANG) REFERENCES FXS_LANG(LANG_CODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_CONTENT_DATA_TPROP(TPROP) REFERENCES FXS_TYPEPROPS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,	
  FOREIGN KEY FK_CONTENT_DATA_FBLOB(FBLOB) REFERENCES FX_BINARY(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_DATA_ID_VER(ID,VER) REFERENCES FX_CONTENT(ID,VER)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_FSELECT(FSELECT) REFERENCES FXS_SELECTLIST_ITEM(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_FREF(FREF) REFERENCES FX_CONTENT(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
--  FOREIGN KEY FK_TDEF(TDEF) REFERENCES FXS_TYPEDEF(ID)
--  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET = LATIN1
ROW_FORMAT=COMPRESSED;

-- Single indexes
CREATE INDEX FXI_CONTENT_DATA_ID ON FX_CONTENT_DATA(ID);
CREATE INDEX FXI_CONTENT_DATA_VER ON FX_CONTENT_DATA(VER);
CREATE INDEX FXI_CONTENT_DATA_LANG ON FX_CONTENT_DATA(LANG);
CREATE INDEX FXI_CONTENT_DATA_ISMAX_VER ON FX_CONTENT_DATA(ISMAX_VER);
CREATE INDEX FXI_CONTENT_DATA_ISLIVE_VER ON FX_CONTENT_DATA(ISLIVE_VER);
CREATE INDEX FXI_CONTENT_DATA_ISGROUP ON FX_CONTENT_DATA(ISGROUP);
CREATE INDEX FXI_CONTENT_DATA_ISMLDEF ON FX_CONTENT_DATA(ISMLDEF);
CREATE INDEX FXI_CONTENT_DATA_XPATH ON FX_CONTENT_DATA(XPATH(1024));
CREATE INDEX FXI_CONTENT_DATA_XPATHMULT ON FX_CONTENT_DATA(XPATHMULT(1024));
CREATE INDEX FXI_CONTENT_DATA_XMULT ON FX_CONTENT_DATA(XMULT(255));
CREATE INDEX FXI_CONTENT_DATA_PARENTXMULT ON FX_CONTENT_DATA(PARENTXMULT(255));
CREATE INDEX FXI_CONTENT_DATA_FCLOB ON FX_CONTENT_DATA(FCLOB(4096));
CREATE INDEX FXI_CONTENT_DATA_UFCLOB ON FX_CONTENT_DATA(UFCLOB(4096));
CREATE INDEX FXI_CONTENT_DATA_FINT ON FX_CONTENT_DATA(FINT);
CREATE INDEX FXI_CONTENT_DATA_FBIGINT ON FX_CONTENT_DATA(FBIGINT);
CREATE INDEX FXI_CONTENT_DATA_FTEXT1024 ON FX_CONTENT_DATA(FTEXT1024(1024));
CREATE INDEX FXI_CONTENT_DATA_UFTEXT1024 ON FX_CONTENT_DATA(UFTEXT1024(1024));
CREATE INDEX FXI_CONTENT_DATA_FDOUBLE ON FX_CONTENT_DATA(FDOUBLE);
CREATE INDEX FXI_CONTENT_DATA_FFLOAT ON FX_CONTENT_DATA(FFLOAT);
CREATE INDEX FXI_CONTENT_DATA_FBOOL ON FX_CONTENT_DATA(FBOOL);
CREATE INDEX FXI_CONTENT_DATA_FDATE1 ON FX_CONTENT_DATA(FDATE1);
CREATE INDEX FXI_CONTENT_DATA_FDATE1_Y ON FX_CONTENT_DATA(FDATE1_Y);
CREATE INDEX FXI_CONTENT_DATA_FDATE1_M ON FX_CONTENT_DATA(FDATE1_M);
CREATE INDEX FXI_CONTENT_DATA_FDATE1_D ON FX_CONTENT_DATA(FDATE1_D);
CREATE INDEX FXI_CONTENT_DATA_FDATE1_HH ON FX_CONTENT_DATA(FDATE1_HH);
CREATE INDEX FXI_CONTENT_DATA_FDATE1_MM ON FX_CONTENT_DATA(FDATE1_MM);
CREATE INDEX FXI_CONTENT_DATA_FDATE1_SS ON FX_CONTENT_DATA(FDATE1_SS);
CREATE INDEX FXI_CONTENT_DATA_FDATE2 ON FX_CONTENT_DATA(FDATE2);
CREATE INDEX FXI_CONTENT_DATA_FDATE2_Y ON FX_CONTENT_DATA(FDATE2_Y);
CREATE INDEX FXI_CONTENT_DATA_FDATE2_M ON FX_CONTENT_DATA(FDATE2_M);
CREATE INDEX FXI_CONTENT_DATA_FDATE2_D ON FX_CONTENT_DATA(FDATE2_D);
CREATE INDEX FXI_CONTENT_DATA_FDATE2_HH ON FX_CONTENT_DATA(FDATE2_HH);
CREATE INDEX FXI_CONTENT_DATA_FDATE2_MM ON FX_CONTENT_DATA(FDATE2_MM);
CREATE INDEX FXI_CONTENT_DATA_FDATE2_SS ON FX_CONTENT_DATA(FDATE2_SS);

-- Combind indexes for the search
CREATE INDEX FXI_CONTENT_DATA_LOAD ON FX_CONTENT_DATA(ID,VER,ISGROUP,XPATHMULT(993));
CREATE INDEX FXI_CD_ASS_FDATE1     ON FX_CONTENT_DATA(ASSIGN,FDATE1);
CREATE INDEX FXI_CD_PRP_FDATE1     ON FX_CONTENT_DATA(TPROP,FDATE1);
CREATE INDEX FXI_CD_ASS_FDATE2     ON FX_CONTENT_DATA(ASSIGN,FDATE2);
CREATE INDEX FXI_CD_PRP_FDATE2     ON FX_CONTENT_DATA(TPROP,FDATE2);
CREATE INDEX FXI_CD_ASS_FINT       ON FX_CONTENT_DATA(ASSIGN,FINT);
CREATE INDEX FXI_CD_PRP_FINT       ON FX_CONTENT_DATA(TPROP,FINT);
CREATE INDEX FXI_CD_ASS_FBIGINT    ON FX_CONTENT_DATA(ASSIGN,FBIGINT);
CREATE INDEX FXI_CD_PRP_FBIGINT    ON FX_CONTENT_DATA(TPROP,FBIGINT);
CREATE INDEX FXI_CD_ASS_FTEXT1024  ON FX_CONTENT_DATA(ASSIGN,FTEXT1024);
CREATE INDEX FXI_CD_PRP_FTEXT1024  ON FX_CONTENT_DATA(TPROP,FTEXT1024);
CREATE INDEX FXI_CD_ASS_UFTEXT1024 ON FX_CONTENT_DATA(ASSIGN,UFTEXT1024);
CREATE INDEX FXI_CD_PRP_UFTEXT1024 ON FX_CONTENT_DATA(TPROP,UFTEXT1024);
CREATE INDEX FXI_CD_ASS_FDOUBLE    ON FX_CONTENT_DATA(ASSIGN,FDOUBLE);
CREATE INDEX FXI_CD_PRP_FDOUBLE    ON FX_CONTENT_DATA(TPROP,FDOUBLE);
CREATE INDEX FXI_CD_ASS_FFLOAT     ON FX_CONTENT_DATA(ASSIGN,FFLOAT);
CREATE INDEX FXI_CD_PRP_FFLOAT     ON FX_CONTENT_DATA(TPROP,FFLOAT);
CREATE INDEX FXI_CD_ASS_FBOOL      ON FX_CONTENT_DATA(ASSIGN,FBOOL);
CREATE INDEX FXI_CD_PRP_FBOOL      ON FX_CONTENT_DATA(TPROP,FBOOL);


CREATE TABLE FX_CONTENT_DATA_FT (
  ID INTEGER UNSIGNED NOT NULL,
  VER smallint(6) NOT NULL,
  LANG SMALLINT UNSIGNED NOT NULL,
--  TDEF INTEGER UNSIGNED NOT NULL,
  ASSIGN INTEGER UNSIGNED NOT NULL,
--  XPATH VARCHAR(1024) NOT NULL,
--  XPATHMULT VARCHAR(1024) NOT NULL,
  XMULT VARCHAR(256) NOT NULL COMMENT 'Multiplicities for each element like 1,1,2,5,etc.',
  VALUE LONGTEXT CHARACTER SET UTF8,
  FULLTEXT(VALUE),
--  PRIMARY KEY PK_DATA(ID,VER,LANG,ASSIGN,XMULT),
  FOREIGN KEY FK_CONTENT_DATA_LANG(LANG) REFERENCES FXS_LANG(LANG_CODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_DATA_ID_VER(ID,VER) REFERENCES FX_CONTENT(ID,VER)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
--  FOREIGN KEY FK_TDEF(TDEF) REFERENCES FXS_TYPEDEF(ID)
--  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=MyISAM
DEFAULT CHARSET = LATIN1
ROW_FORMAT=COMPRESSED;

CREATE INDEX FXI_CONTENT_DATA_FT_ID ON FX_CONTENT_DATA_FT(ID);
CREATE INDEX FXI_CONTENT_DATA_FT_VER ON FX_CONTENT_DATA_FT(VER);
CREATE INDEX FXI_CONTENT_DATA_FT_LANG ON FX_CONTENT_DATA_FT(LANG);
--CREATE INDEX FXI_CONTENT_DATA_FT_XPATHMULT ON FX_CONTENT_DATA_FT(XPATHMULT(256));
--CREATE INDEX FXI_CONTENT_DATA_FT_XPATH ON FX_CONTENT_DATA_FT(XPATH(1024));
CREATE INDEX FXI_CONTENT_DATA_FT_XMULT ON FX_CONTENT_DATA_FT(XMULT(256));
CREATE INDEX FXI_CONTENT_DATA_FT_VALUE ON FX_CONTENT_DATA_FT(VALUE(4096));

-- -------------------------
-- SQL Search
-- -------------------------
CREATE TABLE FXS_SEARCHCACHE_MEMORY (
  SEARCH_ID INTEGER UNSIGNED NOT NULL,
  ID  INTEGER UNSIGNED NOT NULL,
  VER  INTEGER UNSIGNED,
  TDEF INTEGER UNSIGNED NOT NULL,
  CREATED_BY  INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(SEARCH_ID,ID,VER)
)
ENGINE = MEMORY
COMMENT = 'memory search result holder';

CREATE TABLE FXS_SEARCHCACHE_PERM (
  SEARCH_ID INTEGER UNSIGNED NOT NULL,
  ID  INTEGER UNSIGNED NOT NULL,
  VER  INTEGER UNSIGNED,
  TDEF INTEGER UNSIGNED NOT NULL,
  CREATED_BY  INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(SEARCH_ID,ID,VER)
)
ENGINE = MyISAM
COMMENT = 'nontransactional (performance) search result holder';


-- -------------------------
-- Briefcase
-- -------------------------
create table FXS_BRIEFCASE (
  ID INTEGER UNSIGNED NOT NULL,
  ICON_ID INTEGER UNSIGNED NOT NULL,
  NAME VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
  DESCRIPTION TEXT CHARACTER SET UTF8 NOT NULL,
  SOURCE_QUERY TEXT CHARACTER SET UTF8,
  ACL INTEGER UNSIGNED,
  MANDATOR INTEGER UNSIGNED NOT NULL,
  CREATED_BY INTEGER UNSIGNED NOT NULL,
  CREATED_AT BIGINT UNSIGNED NOT NULL,
  MODIFIED_BY INTEGER UNSIGNED NOT NULL,
  MODIFIED_AT BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY(ID),
  -- UNIQUE UNKEY_BRIEFCASE_NAMEOWNER (NAME,CREATED_BY),
  FOREIGN KEY FK_BRIEFCASE_ACL(ACL) REFERENCES FXS_ACL(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_BRIEFCASE_MANDATOR(MANDATOR) REFERENCES FXS_MANDATOR(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET=LATIN1
COMMENT = 'briefcase';

create table FXS_BRIEFCASE_DATA (
  BRIEFCASE_ID INTEGER UNSIGNED NOT NULL,
  ID  INTEGER UNSIGNED NOT NULL,  
  POS INTEGER UNSIGNED NOT NULL,
  AMOUNT INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(BRIEFCASE_ID,ID),
  FOREIGN KEY FK_BRIEFCASE_ID(BRIEFCASE_ID) REFERENCES FXS_BRIEFCASE(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FK_BRIEFCASE_CONTENT_ID(ID) REFERENCES FX_CONTENT(ID) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET=LATIN1
COMMENT = 'briefcase content';


-- -------------------------
-- Groovy scripts table
-- -------------------------

CREATE TABLE FXS_SCRIPTS (
    ID INTEGER UNSIGNED NOT NULL,
	SNAME VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
	SDESC TEXT CHARACTER SET UTF8,
	SDATA LONGTEXT CHARACTER SET UTF8,
	STYPE INTEGER UNSIGNED,
	ACTIVE BOOLEAN NOT NULL,
	PRIMARY KEY PK_SCRIPTS(ID),
	UNIQUE KEY UK_SCRIPT_NAME(SNAME)
)
ENGINE=InnoDB
DEFAULT CHARSET=LATIN1
ROW_FORMAT=COMPRESSED;

CREATE INDEX FXI_SCRIPTS_ID ON FXS_SCRIPTS(ID);
CREATE INDEX FXI_SCRIPTS_NAME ON FXS_SCRIPTS(SNAME);
CREATE INDEX FXI_SCRIPTS_TYPE ON FXS_SCRIPTS(STYPE);

-- ------------------------------------------
-- Groovy scriptmapping table for assignments
-- ------------------------------------------

CREATE TABLE FXS_SCRIPT_ASS_MAPPING (
    ASSIGNMENT INTEGER UNSIGNED NOT NULL,
    SCRIPT INTEGER UNSIGNED NOT NULL,
    DERIVED_USAGE BOOLEAN NOT NULL COMMENT 'Use in derived assignments as well?',
	ACTIVE BOOLEAN NOT NULL,
	STYPE INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY PK_SCRIPT_MAPPING(ASSIGNMENT,SCRIPT,STYPE),
	FOREIGN KEY FK_SCRIPT_MAP_ASS(ASSIGNMENT) REFERENCES FXS_ASSIGNMENTS(ID)
  	ON DELETE CASCADE ON UPDATE RESTRICT,
  	FOREIGN KEY FK_SCRIPT_MAP_SCRIPT(SCRIPT) REFERENCES FXS_SCRIPTS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET=LATIN1
ROW_FORMAT=COMPRESSED;

CREATE INDEX FXI_SCRIPTMAP_ASS ON FXS_SCRIPT_ASS_MAPPING(ASSIGNMENT);
CREATE INDEX FXI_SCRIPTMAP_SCRIPT ON FXS_SCRIPT_ASS_MAPPING(SCRIPT);
CREATE INDEX FXI_SCRIPTMAP_ACTIVE ON FXS_SCRIPT_ASS_MAPPING(ACTIVE);
CREATE INDEX FXI_SCRIPTMAP_STYPE ON FXS_SCRIPT_ASS_MAPPING(STYPE);

-- ------------------------------------
-- Groovy scriptmapping table for types
-- ------------------------------------

CREATE TABLE FXS_SCRIPT_TYPE_MAPPING (
    TYPEDEF INTEGER UNSIGNED NOT NULL,
    SCRIPT INTEGER UNSIGNED NOT NULL,
    DERIVED_USAGE BOOLEAN NOT NULL COMMENT 'Use in derived types as well?',
	ACTIVE BOOLEAN NOT NULL,
	STYPE INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY PK_SCRIPT_TYPE_MAPPING(TYPEDEF,SCRIPT,STYPE),
	FOREIGN KEY FK_SCRIPT_TYPE_MAP_ASS(TYPEDEF) REFERENCES FXS_TYPEDEF(ID)
  	ON DELETE CASCADE ON UPDATE RESTRICT,
  	FOREIGN KEY FK_SCRIPT_TYPE_MAP_SCRIPT(SCRIPT) REFERENCES FXS_SCRIPTS(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET=LATIN1
ROW_FORMAT=COMPRESSED;

CREATE INDEX FXI_SCRIPTMAP_TYPEDEF ON FXS_SCRIPT_TYPE_MAPPING(TYPEDEF);
CREATE INDEX FXI_SCRIPTMAP_SCRIPT  ON FXS_SCRIPT_TYPE_MAPPING(SCRIPT);
CREATE INDEX FXI_SCRIPTMAP_ACTIVE  ON FXS_SCRIPT_TYPE_MAPPING(ACTIVE);


-- -------------------------
-- User configuration table
-- -------------------------

CREATE TABLE FXS_USERCONFIGURATION (
	USER_ID INTEGER UNSIGNED NOT NULL,
	CPATH VARCHAR(255) NOT NULL,
	CKEY VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
	CVALUE LONGTEXT CHARACTER SET UTF8,
	PRIMARY KEY PK_USERCONFIGURATION(USER_ID, CPATH, CKEY),
	FOREIGN KEY FK_USERCONFIG_ID(USER_ID) REFERENCES FXS_ACCOUNTS(ID)
		ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET = LATIN1
COMMENT = 'Per-user configuration table';

-- -------------------------
-- Division configuration table
-- -------------------------

CREATE TABLE FXS_DIVISIONCONFIGURATION (
	CPATH VARCHAR(255) NOT NULL,
	CKEY VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
	CVALUE LONGTEXT CHARACTER SET UTF8,
	PRIMARY KEY PK_DIVISIONCONFIGURATION(CPATH, CKEY)
)
ENGINE = InnoDB
DEFAULT CHARSET = LATIN1
COMMENT = 'Global division configuration table';

-- -------------------------
-- References to FX_CONTENT
-- -------------------------

ALTER TABLE FXS_MANDATOR ADD FOREIGN KEY FK_MAND_META (METADATA) REFERENCES FX_CONTENT (ID)
 ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE FXS_TYPEDEF ADD FOREIGN KEY FK_ICON_REF (ICON_REF) REFERENCES FX_CONTENT (ID)
 ON DELETE RESTRICT ON UPDATE RESTRICT;

-- -------------------------
-- Edit Tree
-- -------------------------
CREATE TABLE FXS_TREE  (
 ID INTEGER UNSIGNED NOT NULL,
 NAME VARCHAR(1024) NOT NULL,
 MODIFIED_AT BIGINT UNSIGNED NOT NULL,
 DIRTY BOOLEAN NOT NULL,
 PARENT INTEGER UNSIGNED,
 DEPTH INTEGER UNSIGNED,
 CHILDCOUNT INTEGER UNSIGNED NOT NULL,
 TOTAL_CHILDCOUNT INTEGER UNSIGNED NOT NULL,
 REF INTEGER UNSIGNED,
 TEMPLATE VARCHAR(2000),
 LFT BIGINT UNSIGNED NOT NULL,
 RGT BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(ID),
 FOREIGN KEY FX_TREE_PARENT(parent) REFERENCES FXS_TREE(id),
 FOREIGN KEY FK_REF(REF) REFERENCES FX_CONTENT(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
) engine=InnoDb;

-- -------------------------
-- Live Tree
-- -------------------------
CREATE TABLE FXS_TREE_LIVE  (
 ID INTEGER UNSIGNED NOT NULL,
 NAME VARCHAR(1024) NOT NULL,
 MODIFIED_AT BIGINT UNSIGNED NOT NULL,
 DIRTY BOOLEAN NOT NULL,
 PARENT INTEGER UNSIGNED,
 DEPTH INTEGER UNSIGNED,
 CHILDCOUNT INTEGER UNSIGNED NOT NULL,
 TOTAL_CHILDCOUNT INTEGER UNSIGNED NOT NULL,
 REF INTEGER UNSIGNED,
 TEMPLATE VARCHAR(2000),
 LFT BIGINT UNSIGNED NOT NULL,
 RGT BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(ID),
 FOREIGN KEY FX_TREE_PARENT(parent) REFERENCES FXS_TREE_LIVE(id),
 FOREIGN KEY FK_REF(REF) REFERENCES FX_CONTENT(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
) engine=InnoDb;


