-- -------------------------
-- Sequenzer  Initialization, next value will be the given id+1
-- -------------------------

CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_CONTENT START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FX_CONTENT) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_ACCOUNT START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_ACCOUNTS) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_GROUP START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_USERGROUPS) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_ACL START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_ACL) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_MANDATOR START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_MANDATOR) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_TYPEDEF START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_TYPEDEF) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_TYPEGROUP START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_TYPEGROUPS) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_TYPEPROP START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_TYPEPROPS) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_ASSIGNMENT START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_ASSIGNMENTS) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_STEPDEFINITION START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_WF_STEPDEFS) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_STEP START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_WF_STEPS) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_ROUTE START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_WF_ROUTES) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_WORKFLOW START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_WORKFLOWS) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_BINARY START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FX_BINARY) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_SCRIPTS START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_SCRIPTS) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_BRIEFCASE START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_BRIEFCASE) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_SEARCHCACHE_MEMORY START WITH (SELECT IFNULL(MAX(SEARCH_ID),0)+1 FROM FXS_SEARCHCACHE_MEMORY) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_SEARCHCACHE_PERM START WITH (SELECT IFNULL(MAX(SEARCH_ID),0)+1 FROM FXS_SEARCHCACHE_PERM) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_SELECTLIST START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_SELECTLIST) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_SELECTLIST_ITEM START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_SELECTLIST_ITEM) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_TREE_EDIT START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_TREE) INCREMENT BY 1 CACHE 16;
CREATE SEQUENCE IF NOT EXISTS FXSEQ_SYS_TREE_LIVE START WITH (SELECT IFNULL(MAX(ID),0)+1 FROM FXS_TREE_LIVE) INCREMENT BY 1 CACHE 16;

