-- Patch from v1248 --> v1299
-- Adds an node-scoped configuration table (FX-558)

CREATE TABLE FXS_NODECONFIGURATION (
    NODE_ID VARCHAR(255) NOT NULL,
	CPATH VARCHAR(255) NOT NULL,
	CKEY VARCHAR(255) NOT NULL,
	CVALUE LONGTEXT,
	PRIMARY KEY (NODE_ID, CPATH, CKEY)
);
COMMENT ON TABLE FXS_NODECONFIGURATION IS 'Node configuration table';
