-- Patch from v1310 --> v1353
-- Change: Add CLASSNAME column to all configuration tables
-- Author: Daniel Lichtenberger (daniel.lichtenberger@flexive.com), UCS - unique computing solutions gmbh (http://www.ucs.at)
ALTER TABLE FXS_DIVISIONCONFIGURATION ADD COLUMN `CLASSNAME` VARCHAR(255) NULL;
ALTER TABLE FXS_APPLICATIONCONFIGURATION ADD COLUMN `CLASSNAME` VARCHAR(255) NULL;
ALTER TABLE FXS_NODECONFIGURATION ADD COLUMN `CLASSNAME` VARCHAR(255) NULL;
ALTER TABLE FXS_USERCONFIGURATION ADD COLUMN `CLASSNAME` VARCHAR(255) NULL;