-- -------------------------
-- Locks (FX-77)
-- -------------------------
CREATE TABLE FXS_LOCK (
  LOCK_ID BIGINT,
  LOCK_VER SMALLINT(6),
  LOCK_RESOURCE VARCHAR(256),
  USER_ID BIGINT NOT NULL,
  LOCKTYPE SMALLINT(6) NOT NULL,
  CREATED_AT BIGINT UNSIGNED NOT NULL,
  EXPIRES_AT BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES FXS_ACCOUNTS(ID)
		ON DELETE CASCADE ON UPDATE RESTRICT,
  FOREIGN KEY (LOCK_ID,LOCK_VER) REFERENCES FX_CONTENT(ID,VER)
        ON DELETE CASCADE ON UPDATE RESTRICT
);
COMMENT ON TABLE FXS_LOCK IS 'Locks';
CREATE INDEX FXI_LOCK_USER_ID ON FXS_LOCK(USER_ID);
CREATE INDEX FXI_LOCK_ID ON FXS_LOCK(LOCK_ID);
CREATE INDEX FXI_LOCK_ID_VER ON FXS_LOCK(LOCK_ID, LOCK_VER);
CREATE INDEX FXI_LOCK_RESOURCE ON FXS_LOCK(LOCK_RESOURCE);
CREATE INDEX FXI_LOCK_EXPIRES ON FXS_LOCK(EXPIRES_AT);