-- Patch from v1166 -> v1248
-- Change: Remove date fields for year, month, day, hour, minute and second to increase performance
-- Author: Markus Plesser (markus.plesser@flexive.com), UCS - unique computing solutions gmbh (http://www.ucs.at)

ALTER TABLE FX_CONTENT_DATA DROP COLUMN FDATE1_Y;
ALTER TABLE FX_CONTENT_DATA DROP COLUMN FDATE1_M;
ALTER TABLE FX_CONTENT_DATA DROP COLUMN FDATE1_D;
ALTER TABLE FX_CONTENT_DATA DROP COLUMN FDATE1_HH;
ALTER TABLE FX_CONTENT_DATA DROP COLUMN FDATE1_MM;
ALTER TABLE FX_CONTENT_DATA DROP COLUMN FDATE1_SS;
ALTER TABLE FX_CONTENT_DATA DROP COLUMN FDATE2_Y;
ALTER TABLE FX_CONTENT_DATA DROP COLUMN FDATE2_M;
ALTER TABLE FX_CONTENT_DATA DROP COLUMN FDATE2_D;
ALTER TABLE FX_CONTENT_DATA DROP COLUMN FDATE2_HH;
ALTER TABLE FX_CONTENT_DATA DROP COLUMN FDATE2_MM;
ALTER TABLE FX_CONTENT_DATA DROP COLUMN FDATE2_SS;