-- Patch from v2824 -> v2859
-- Change: phrase engine: categories support
-- Author: Markus Plesser (markus.plesser@flexive.com), UCS - unique computing solutions gmbh (http://www.ucs.at)
ALTER TABLE FX_PHRASE_MAP DROP CONSTRAINT FX_PHRASE_MAP_PKEY;
ALTER TABLE FX_PHRASE_MAP ADD COLUMN CAT INTEGER NOT NULL DEFAULT 0;
ALTER TABLE FX_PHRASE_MAP ADD PRIMARY KEY (MANDATOR, CAT, NODEID, NODEMANDATOR, PHRASEID, PMANDATOR);
ALTER TABLE FX_PHRASE_TREE DROP CONSTRAINT FX_PHRASE_TREE_PKEY;
ALTER TABLE FX_PHRASE_TREE ADD PRIMARY KEY (ID, MANDATOR, CAT);