-- Patch from v2248 --> v2273
-- Change: Added script schedules table
-- Author: Gerhard Glos (gerhard.glos@flexive.com), UCS - unique computing solutions gmbh (http://www.ucs.at)

CREATE TABLE FXS_SCRIPT_SCHEDULES (
    ID BIGINT NOT NULL,
	SCRIPT BIGINT NOT NULL,
    SNAME VARCHAR(255),
    ACTIVE BOOLEAN NOT NULL,
	STARTTIME TIMESTAMP(3) NOT NULL,
    ENDTIME TIMESTAMP(3),
    REPEATINTERVAL BIGINT NOT NULL,
    REPEATTIMES INTEGER NOT NULL,
    CRONSTRING VARCHAR(255),
	PRIMARY KEY (ID),
    FOREIGN KEY (SCRIPT) REFERENCES FXS_SCRIPTS(ID)
  	    ON DELETE RESTRICT ON UPDATE RESTRICT
);
COMMENT ON TABLE FXS_SCRIPT_SCHEDULES IS 'Script Schedules';

CREATE INDEX FXS_SCRIPT_SCHEDULES_ID ON FXS_SCRIPT_SCHEDULES(ID);