-- Patch from v2646 -> v2738
-- Change: briefcase item meta data support
-- Author: Markus Plesser (markus.plesser@flexive.com), UCS - unique computing solutions gmbh (http://www.ucs.at)
CREATE TABLE FXS_BRIEFCASE_DATA_ITEM (
  BRIEFCASE_ID BIGINT NOT NULL,
  ID INTEGER NOT NULL,
  POS INTEGER NOT NULL,
  INTFLAG1 INTEGER NULL,
  INTFLAG2 INTEGER NULL,
  INTFLAG3 INTEGER NULL,
  LONGFLAG1 BIGINT NULL,
  LONGFLAG2 BIGINT NULL,
  METADATA VARCHAR(1024) NULL,
  PRIMARY KEY(BRIEFCASE_ID,ID,POS),
  FOREIGN KEY (BRIEFCASE_ID) REFERENCES FXS_BRIEFCASE(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
COMMENT ON TABLE FXS_BRIEFCASE_DATA_ITEM IS 'briefcase item meta data';