-- Patch from v2273 -> v2378
-- Change: FX-908: FX_RES Resource table
-- Author: Markus Plesser (markus.plesser@flexive.com), UCS - unique computing solutions gmbh (http://www.ucs.at)

CREATE TABLE FX_RES (
  RKEY VARCHAR(50) NOT NULL,
  LANG SMALLINT UNSIGNED NOT NULL,
  RVAL TEXT CHARACTER SET UTF8 NOT NULL,
  UNIQUE KEY RES_KEY(RKEY, LANG),
  FOREIGN KEY FK_RES_LANG(LANG) REFERENCES FXS_LANG(LANG_CODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET=LATIN1 COLLATE=LATIN1_BIN
COMMENT='Resources'
ROW_FORMAT=FIXED;
CREATE INDEX FXI_RES_KEY ON FX_RES(RKEY);