-- Patch from v2646 -> v2738
-- Change: briefcase item meta data support
-- Author: Markus Plesser (markus.plesser@flexive.com), UCS - unique computing solutions gmbh (http://www.ucs.at)
CREATE TABLE FXS_BRIEFCASE_DATA_ITEM (
  BRIEFCASE_ID INTEGER UNSIGNED NOT NULL,
  ID BIGINT NOT NULL,
  POS INTEGER UNSIGNED NOT NULL,
  INTFLAG1 INTEGER NULL,
  INTFLAG2 INTEGER NULL,
  INTFLAG3 INTEGER NULL,
  LONGFLAG1 BIGINT NULL,
  LONGFLAG2 BIGINT NULL,
  METADATA VARCHAR(1024) CHARACTER SET UTF8 NULL,
  PRIMARY KEY(BRIEFCASE_ID,ID,POS),
  FOREIGN KEY (BRIEFCASE_ID) REFERENCES FXS_BRIEFCASE(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARSET=LATIN1
COMMENT = 'briefcase item meta data';