-- Patch from v2562 -> v2641
-- Change: Mandator specific phrase management
-- Author: Markus Plesser (markus.plesser@flexive.com), UCS - unique computing solutions gmbh (http://www.ucs.at)

-- -------------------------
-- PHRASES
-- -------------------------
CREATE TABLE FX_PHRASE (
  ID INTEGER UNSIGNED NOT NULL,
  MANDATOR INTEGER UNSIGNED NOT NULL,
  PKEY VARCHAR(250) NOT NULL,
  PRIMARY KEY(ID, MANDATOR),
  FOREIGN KEY FK_PHRASE_MANDATOR(MANDATOR) REFERENCES FXS_MANDATOR(ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT,
  UNIQUE KEY UNIQUE_PKEY(ID,MANDATOR,PKEY)
)
ENGINE=InnoDB
DEFAULT CHARSET=LATIN1 COLLATE=LATIN1_BIN
COMMENT='Phrases'
ROW_FORMAT=FIXED;
CREATE INDEX FXI_PHRASE_KEY ON FX_PHRASE(MANDATOR, PKEY);

-- -------------------------
-- PHRASE VALUES
-- -------------------------
CREATE TABLE FX_PHRASE_VAL (
  ID INTEGER UNSIGNED NOT NULL,
  MANDATOR INTEGER UNSIGNED NOT NULL,
  LANG SMALLINT UNSIGNED NOT NULL,
  PVAL TEXT CHARACTER SET UTF8 NOT NULL,
  TAG VARCHAR(250) CHARACTER SET UTF8,
  PRIMARY KEY(ID,MANDATOR,LANG),
  FOREIGN KEY FX_PHRASE_VAL_ID_MANDATOR(ID,MANDATOR) REFERENCES FX_PHRASE(ID,MANDATOR)
    ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FX_PHRASE_VAL_LANG(LANG) REFERENCES FXS_LANG(LANG_CODE)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY FX_PHRASE_VAL_MANDATOR(MANDATOR) REFERENCES FXS_MANDATOR(ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET=LATIN1 COLLATE=LATIN1_BIN
COMMENT='Phrase values'
ROW_FORMAT=FIXED;

-- -------------------------
-- PHRASE TREE
-- -------------------------
CREATE TABLE FX_PHRASE_TREE (
  ID INTEGER UNSIGNED NOT NULL,
  MANDATOR INTEGER UNSIGNED NOT NULL,
  PARENTID INTEGER UNSIGNED,
  PARENTMANDATOR INTEGER UNSIGNED,
  PHRASEID INTEGER UNSIGNED NOT NULL,
  PMANDATOR INTEGER UNSIGNED NOT NULL,
  POS INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY(ID, MANDATOR),
  FOREIGN KEY (MANDATOR) REFERENCES FXS_MANDATOR(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY (PARENTMANDATOR) REFERENCES FXS_MANDATOR(ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY (PHRASEID, PMANDATOR) REFERENCES FX_PHRASE(ID, MANDATOR)
    ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY (PMANDATOR) REFERENCES FXS_MANDATOR(ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET=LATIN1 COLLATE=LATIN1_BIN
COMMENT='Phrase Tree'
ROW_FORMAT=FIXED;

-- -------------------------
-- PHRASE MAPPING
-- -------------------------
CREATE TABLE FX_PHRASE_MAP (
  MANDATOR INTEGER UNSIGNED NOT NULL,
  NODEID INTEGER UNSIGNED NOT NULL,
  NODEMANDATOR INTEGER UNSIGNED NOT NULL,
  PHRASEID INTEGER UNSIGNED NOT NULL,
  PMANDATOR INTEGER UNSIGNED NOT NULL,
  POS INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY(MANDATOR, NODEID, NODEMANDATOR, PHRASEID, PMANDATOR),
  FOREIGN KEY (MANDATOR) REFERENCES FXS_MANDATOR(ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY (NODEMANDATOR) REFERENCES FXS_MANDATOR(ID)
  	ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY (PMANDATOR) REFERENCES FXS_MANDATOR(ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY (PHRASEID,PMANDATOR) REFERENCES FX_PHRASE(ID,MANDATOR)
    ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
DEFAULT CHARSET=LATIN1 COLLATE=LATIN1_BIN
COMMENT='Phrase Mapping'
ROW_FORMAT=FIXED;
CREATE INDEX FXI_PHRASE_MAP_KEY ON FX_PHRASE_MAP(PHRASEID, PMANDATOR);
CREATE INDEX FXI_PHRASE_MAP_POS ON FX_PHRASE_MAP(NODEMANDATOR, POS);