-- Patch from v2222 -> v2248
-- Change: FX-873: Update Quartz to 1.8
-- Author: Markus Plesser (markus.plesser@flexive.com), UCS - unique computing solutions gmbh (http://www.ucs.at)
ALTER TABLE QRTZ_JOB_DETAILS CHANGE COLUMN JOB_NAME JOB_NAME VARCHAR(200);
ALTER TABLE QRTZ_JOB_DETAILS CHANGE COLUMN JOB_GROUP JOB_GROUP VARCHAR(200);
ALTER TABLE QRTZ_JOB_DETAILS CHANGE COLUMN DESCRIPTION DESCRIPTION VARCHAR(200);
ALTER TABLE QRTZ_JOB_DETAILS CHANGE COLUMN JOB_CLASS_NAME JOB_CLASS_NAME VARCHAR(250);

ALTER TABLE QRTZ_JOB_LISTENERS CHANGE COLUMN JOB_NAME JOB_NAME VARCHAR(200);
ALTER TABLE QRTZ_JOB_LISTENERS CHANGE COLUMN JOB_GROUP JOB_GROUP VARCHAR(200);
ALTER TABLE QRTZ_JOB_LISTENERS CHANGE COLUMN JOB_LISTENER JOB_LISTENER VARCHAR(200);

ALTER TABLE QRTZ_TRIGGERS CHANGE COLUMN TRIGGER_NAME TRIGGER_NAME VARCHAR(200);
ALTER TABLE QRTZ_TRIGGERS CHANGE COLUMN TRIGGER_GROUP TRIGGER_GROUP VARCHAR(200);
ALTER TABLE QRTZ_TRIGGERS CHANGE COLUMN JOB_NAME JOB_NAME VARCHAR(200);
ALTER TABLE QRTZ_TRIGGERS CHANGE COLUMN JOB_GROUP JOB_GROUP VARCHAR(200);
ALTER TABLE QRTZ_TRIGGERS CHANGE COLUMN DESCRIPTION DESCRIPTION VARCHAR(250);
ALTER TABLE QRTZ_TRIGGERS CHANGE COLUMN CALENDAR_NAME CALENDAR_NAME VARCHAR(200);

ALTER TABLE QRTZ_SIMPLE_TRIGGERS CHANGE COLUMN TRIGGER_NAME TRIGGER_NAME VARCHAR(200);
ALTER TABLE QRTZ_SIMPLE_TRIGGERS CHANGE COLUMN TRIGGER_GROUP TRIGGER_GROUP VARCHAR(200);

ALTER TABLE QRTZ_CRON_TRIGGERS CHANGE COLUMN TRIGGER_NAME TRIGGER_NAME VARCHAR(200);
ALTER TABLE QRTZ_CRON_TRIGGERS CHANGE COLUMN TRIGGER_GROUP TRIGGER_GROUP VARCHAR(200);
ALTER TABLE QRTZ_CRON_TRIGGERS CHANGE COLUMN CRON_EXPRESSION CRON_EXPRESSION VARCHAR(120);

ALTER TABLE QRTZ_BLOB_TRIGGERS CHANGE COLUMN TRIGGER_NAME TRIGGER_NAME VARCHAR(200);
ALTER TABLE QRTZ_BLOB_TRIGGERS CHANGE COLUMN TRIGGER_GROUP TRIGGER_GROUP VARCHAR(200);

ALTER TABLE QRTZ_TRIGGER_LISTENERS CHANGE COLUMN TRIGGER_NAME TRIGGER_NAME VARCHAR(200);
ALTER TABLE QRTZ_TRIGGER_LISTENERS CHANGE COLUMN TRIGGER_GROUP TRIGGER_GROUP VARCHAR(200);
ALTER TABLE QRTZ_TRIGGER_LISTENERS CHANGE COLUMN TRIGGER_LISTENER TRIGGER_LISTENER VARCHAR(200);

ALTER TABLE QRTZ_CALENDARS CHANGE COLUMN CALENDAR_NAME CALENDAR_NAME VARCHAR(200);

ALTER TABLE QRTZ_PAUSED_TRIGGER_GRPS CHANGE COLUMN TRIGGER_GROUP TRIGGER_GROUP VARCHAR(200);

ALTER TABLE QRTZ_FIRED_TRIGGERS CHANGE COLUMN TRIGGER_NAME TRIGGER_NAME VARCHAR(200);
ALTER TABLE QRTZ_FIRED_TRIGGERS CHANGE COLUMN TRIGGER_GROUP TRIGGER_GROUP VARCHAR(200);
ALTER TABLE QRTZ_FIRED_TRIGGERS CHANGE COLUMN INSTANCE_NAME INSTANCE_NAME VARCHAR(200);
ALTER TABLE QRTZ_FIRED_TRIGGERS CHANGE COLUMN JOB_NAME JOB_NAME VARCHAR(200);
ALTER TABLE QRTZ_FIRED_TRIGGERS CHANGE COLUMN JOB_GROUP JOB_GROUP VARCHAR(200);

ALTER TABLE QRTZ_SCHEDULER_STATE CHANGE COLUMN INSTANCE_NAME INSTANCE_NAME VARCHAR(200);