-- -------------------------
-- Locks (FX-77)
-- LOCK_ID has to be INTEGER UNSIGNED, else patching does not work and MySQL will report error 150 ... (weird!)
-- -------------------------
CREATE TABLE FXS_LOCK (
  LOCK_ID INTEGER UNSIGNED,
  LOCK_VER SMALLINT(6),
  LOCK_RESOURCE VARCHAR(256) CHARACTER SET UTF8,
  USER_ID INTEGER UNSIGNED NOT NULL,
  LOCKTYPE SMALLINT(6) NOT NULL,
  CREATED_AT BIGINT UNSIGNED NOT NULL,
  EXPIRES_AT BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY FK_LOCK_USER_ID(USER_ID) REFERENCES FXS_ACCOUNTS(ID)
		ON DELETE CASCADE ON UPDATE RESTRICT,
  FOREIGN KEY FK_LOCK_ID_VER(LOCK_ID,LOCK_VER) REFERENCES FX_CONTENT(ID,VER)
        ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = InnoDB DEFAULT CHARSET=LATIN1 COMMENT = 'Locks';

CREATE INDEX FXI_LOCK_USER_ID ON FXS_LOCK(USER_ID);
CREATE INDEX FXI_LOCK_ID ON FXS_LOCK(LOCK_ID);
CREATE INDEX FXI_LOCK_ID_VER ON FXS_LOCK(LOCK_ID, LOCK_VER);
CREATE INDEX FXI_LOCK_RESOURCE ON FXS_LOCK(LOCK_RESOURCE);
CREATE INDEX FXI_LOCK_EXPIRES ON FXS_LOCK(EXPIRES_AT);