-- Patch from v2248 --> v2273
-- Change: Added script schedules table
-- Author: Gerhard Glos (gerhard.glos@flexive.com), UCS - unique computing solutions gmbh (http://www.ucs.at)

CREATE TABLE FXS_SCRIPT_SCHEDULES (
    ID INTEGER UNSIGNED NOT NULL,
	SCRIPT INTEGER UNSIGNED NOT NULL,
    SNAME VARCHAR(255) CHARACTER SET UTF8,
    ACTIVE BOOLEAN NOT NULL,
	STARTTIME DATETIME NOT NULL,
    ENDTIME DATETIME,
    REPEATINTERVAL BIGINT NOT NULL,
    REPEATTIMES INTEGER NOT NULL,
    CRONSTRING VARCHAR(255) CHARACTER SET UTF8,
	PRIMARY KEY (ID),
    FOREIGN KEY FK_SCRIPT_SCHEDULE_SCRIPT(SCRIPT) REFERENCES FXS_SCRIPTS(ID)
  	    ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE=InnoDB
COMMENT='Script Schedules'
DEFAULT CHARSET=LATIN1
ROW_FORMAT=COMPRESSED;

CREATE INDEX FXS_SCRIPT_SCHEDULES_ID ON FXS_SCRIPT_SCHEDULES(ID);